/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User.Interface.SupplierShippingRole;

import Business.Enterprise.InventoryEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Order.Order;
import Business.Order.OrderItem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asha
 */
public class ManageOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrdersJPanel
     */
    private JPanel userProcessContainer;
    private InventoryEnterprise inventoryEnterprise;
    private SupplierEnterprise supplierEnterprise;

    public ManageOrdersJPanel(JPanel userProcessContainer, SupplierEnterprise supplierEnterprise, InventoryEnterprise inventoryEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierEnterprise = supplierEnterprise;
        this.inventoryEnterprise = inventoryEnterprise;
         Color c = new Color(0, 85, 119);
        this.setBackground(c);
        populateOrderTable();
    }

    private void populateOrderTable() {
        int rowCount = detailsorderJTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) orderJTable.getModel();

        //delete all the previous rows
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (Order o : supplierEnterprise.getOrderQueue().getOrderList()) {
            Object[] row = new Object[1];
            row[0] = o;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsorderJTable = new javax.swing.JTable();
        processOrderjButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 85, 119));
        setForeground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(255, 255, 255));
        titlejLabel.setText("Supplier Admin - Manage Orders");

        detailsorderJTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        detailsorderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device Name", "Price", "Quantity", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailsorderJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(detailsorderJTable);

        processOrderjButton.setBackground(new java.awt.Color(30, 30, 30));
        processOrderjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        processOrderjButton.setForeground(new java.awt.Color(255, 255, 255));
        processOrderjButton.setText("Ship Order");
        processOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processOrderjButtonActionPerformed(evt);
            }
        });

        orderJTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID"
            }
        ));
        orderJTable.getTableHeader().setReorderingAllowed(false);
        orderJTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                orderJTableFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(orderJTable);

        backjButton.setBackground(new java.awt.Color(30, 30, 30));
        backjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backjButton.setForeground(new java.awt.Color(255, 255, 255));
        backjButton.setText("<< Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titlejLabel)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(processOrderjButton)))
                        .addGap(46, 46, 46)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titlejLabel)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processOrderjButton)
                    .addComponent(backjButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processOrderjButtonActionPerformed
        // TODO add your handling code here:

        //get the selected order
        int selectedRow = orderJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order from the list");
            return;
        }

        //get the selected order  
        Order o = (Order) orderJTable.getValueAt(selectedRow, 0);
        if (null == o) {
            JOptionPane.showMessageDialog(this, "Failed to retrieve selected order's information");
            return;
        }

        //set the order in inventory deliveries list
        inventoryEnterprise.getOrderDelivery().addOrder(o);
        JOptionPane.showMessageDialog(this, "Order has been shipped");
    }//GEN-LAST:event_processOrderjButtonActionPerformed

    private void orderJTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_orderJTableFocusGained
        // TODO add your handling code here:
        populateDetailsOrderTable();
    }//GEN-LAST:event_orderJTableFocusGained

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void populateDetailsOrderTable() {

        //get the selected order
        int selectedRow = orderJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order from the list");
            return;
        }

        Order o = (Order) orderJTable.getValueAt(selectedRow, 0);
        if (null == o) {
            JOptionPane.showMessageDialog(this, "Failed to retrieve selected order's information");
            return;
        }

        int rowCount = detailsorderJTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) detailsorderJTable.getModel();

        //delete all the previous rows
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (OrderItem oi : o.getOrderItemList()) {
            Object[] row = new Object[4];
            row[0] = oi;
            row[1] = oi.getMedicalDevice().getPrice();
            row[2] = oi.getQuantity();
            row[3] = (oi.getMedicalDevice().getPrice() * oi.getQuantity());
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTable detailsorderJTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable orderJTable;
    private javax.swing.JButton processOrderjButton;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
