/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User.Interface.SupplierShippingRole;

import Business.Enterprise.InventoryEnterprise;
import Business.Enterprise.SupplierEnterprise;
import static Business.Organization.Organization.Type.SupplierShippingOrganization;
import Business.Organization.SupplierShippingOrganization;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Asha
 */
public class SupplierShippingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierShippingWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private SupplierEnterprise supplierEnterprise;
    private InventoryEnterprise inventoryEnterprise;
    public SupplierShippingWorkAreaJPanel( JPanel userProcessContainer, SupplierEnterprise supplierEnterprise, InventoryEnterprise inventoryEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierEnterprise = supplierEnterprise;         
        this.inventoryEnterprise = inventoryEnterprise;
         Color c = new Color(0, 85, 119);
        this.setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel = new javax.swing.JLabel();
        manageOrdersjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 85, 119));
        setForeground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(255, 255, 255));
        titlejLabel.setText("Supplier Shipping Work Area");

        manageOrdersjButton.setBackground(new java.awt.Color(30, 30, 30));
        manageOrdersjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageOrdersjButton.setText("Manage Orders");
        manageOrdersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(titlejLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(manageOrdersjButton)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titlejLabel)
                .addGap(63, 63, 63)
                .addComponent(manageOrdersjButton)
                .addContainerGap(402, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrdersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersjButtonActionPerformed
        // TODO add your handling code here:
         ManageOrdersJPanel panel = new ManageOrdersJPanel(userProcessContainer,supplierEnterprise,inventoryEnterprise);
        userProcessContainer.add("ManageOrdersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_manageOrdersjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageOrdersjButton;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
