//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PASCOM.rc
//
#define IDS_PAS_FOLDER                  1001
#define IDS_PAS_FILENAME                1002
#define IDS_SEQ_FILENAME                1003
#define IDS_XML_EXT                     1004
#define IDS_TAG_CHILD_ID                1005
#define IDS_TAG_CHILD_POSITIONS         1006
#define IDS_PAS_XML                     1007
#define IDS_TAG_NAME                    1008
#define IDS_SEQ_XML                     1009
#define IDS_TAG_POS                     1010
#define IDS_SEQ_XML1                    1011
#define IDS_CONTAINER_XML               1012
#define IDS_CONTAINER_FILENAME          1013
#define IDS_PQM_APP_NAME                1014
#define IDS_APPLICATION_NOTFOUND        1015
#define IDS_COMM_CHANNEL                1016
#define IDS_DLL_DEBUG                   1017
#define IDS_DLL_RELEASE                 1018
#define IDS_SEQ_RECEIVED                1019
#define IDS_SEQ_COMM                    1500
#define IDS_SEQ_SEQ                     1501
#define IDS_SEQ_SCAN_ID                 1502
#define IDS_SEQ_SA                      1503
#define IDS_SEQ_PORI                    1504
#define IDS_SEQ_TC                      1505
#define IDS_SEQ_RC                      1506
#define IDS_SEQ_TR                      1507
#define IDS_SEQ_FAT                     1508
#define IDS_SEQ_THK                     1509
#define IDS_SEQ_GAP                     1510
#define IDS_SEQ_MTX                     1511
#define IDS_SEQ_FOV                     1512
#define IDS_SEQ_TS                      1513
#define IDS_SEQ_WRAP                    1514
#define IDS_SEQ_NAQ                     1515
#define IDS_SEQ_PLN                     1516
#define IDS_SEQ_FLIP                    1517
#define IDS_SEQ_SPSAT                   1518
#define IDS_SEQ_ITRL                    1519
#define IDS_SEQ_ACQ                     1520
#define IDS_SEQ_AFI                     1521
#define IDS_SEQ_KFLT                    1522
#define IDS_SEQ_RFLT                    1523
#define IDS_SEQ_ROPRC                   1524
#define IDS_SEQ_PEPRC                   1525
#define IDS_SEQ_SEPRC                   1526
#define IDS_SEQ_PDATAF                  1527
#define IDS_SEQ_VDIR                    1528
#define IDS_SEQ_PVOICE                  1529
#define IDS_SEQ_MIP                     1530
#define IDS_SEQ_MIPB                    1531
#define IDS_SEQ_MIPANG                  1532
#define IDS_SEQ_MIPSL                   1533
#define IDS_SEQ_MAXP                    1534
#define IDS_SEQ_COV                     1535
#define IDS_SEQ_SKIP                    1536
#define IDS_SEQ_HOLD                    1537
#define IDS_SEQ_GTAG                    1538
#define IDS_SEQ_RECON                   1539
#define IDS_SEQ_SCMD                    1540
#define IDS_SEQ_SPEED                   1541
#define IDS_SEQ_MTC                     1542
#define IDS_SEQ_COUCH                   1543
#define IDS_SEQ_PREP                    1544
#define IDS_SEQ_BVAL                    1545
#define IDS_SEQ_RFSPOIL                 1546
#define IDS_SEQ_SPDR                    1547
#define IDS_SEQ_FATTYPE                 1548
#define IDS_SEQ_SPLITM                  1549
#define IDS_SEQ_DRKS                    1550
#define IDS_SEQ_GDCFLG                  1551
#define IDS_SEQ_ALTFLG                  1552
#define IDS_SEQ_RMC                     1553
#define IDS_SEQ_LCFFLG                  1554
#define IDS_SEQ_FCMP                    1555
#define IDS_SEQ_WEFLG                   1556
#define IDS_SEQ_TRIGT                   1557
#define IDS_SEQ_FLEXTE                  1558
#define IDS_SEQ_BW                      1559
#define IDS_SEQ_NRFLG                   1560
#define IDS_SEQ_NRSET                   1561
#define IDS_SEQ_GOPFLT                  1562
#define IDS_SEQ_KFLTNR                  1563
#define IDS_SEQ_MIPFLT                  1564
#define IDS_SEQ_MIPGOP                  1565
#define IDS_SEQ_GDC                     1566
#define IDS_SEQ_GDCIMG                  1567
#define IDS_SEQ_GDCMASK                 1568
#define IDS_SEQ_MAXPCOV                 1569
#define IDS_SEQ_PEORDER                 1570
#define IDS_SEQ_SPDRT                   1571
#define IDS_SEQ_INTCORF                 1572
#define IDS_SEQ_INTCORR                 1573
#define IDS_SEQ_SPDRR_RO                1574
#define IDS_SEQ_SPDRR_PE                1575
#define IDS_SEQ_SPDRR_SE                1576
#define IDS_SEQ_WRAPR_RO                1577
#define IDS_SEQ_WRAPR_PE                1578
#define IDS_SEQ_WRAPR_SE                1579
#define IDS_SEQ_SPDRRI_RO               1580
#define IDS_SEQ_SPDRRI_PE               1581
#define IDS_SEQ_SPDRRI_SE               1582
#define IDR_SEQ_PARAM                   2002
#define IDS_ERR_INTERNAL_ERROR          5000
#define IDS_ERR_SEQ_LIST_EMPTY          5001
#define IDS_ERR_RESOURCE_FAILED         5002
#define IDS_ERR_PATH_IS_EMPTY           5003
#define IDS_ERR_INTERNAL_XML_ERROR      5004
#define IDS_ERR_NODE_NOT_FOUND          5005
#define IDS_ERR_BLANK                   5006
#define IDS_ERR_FILE_OPERATION          5007
#define IDS_ERR_COMM                    5008
#define IDS_ERR_XML_PATH_EMPTY          5009
#define IDS_ERR_MSXML_COM               5010
#define IDS_ERR_SAVE_FAILED             5011
#define IDS_ERR_FILE_OPEN               5012
#define IDS_ERR_PAS_CREATION_FAILED     5013
#define IDS_ERR_XML_LOADING_FAILED      5014
#define IDS_ERR_ATTR_NOT_FOUND          5015
#define IDS_ERR_NODE_LIST_NOT_FOUND     5016
#define IDS_ERR_XML_SAVING_FAILED       5017
#define IDS_ERR_CREATE_NODE_FAILED      5018
#define IDS_ERR_APPEND_NODE_FAILED      5019
#define IDS_ERR_OUTOFMEMORY             5020
#define IDS_ERR_PAS_NAME_EMPTY          5021
#define IDS_ERR_PAS_UID_EMPTY           5022
#define IDS_ERR_PAS_CONTAINER_PATH_EMPTY 5023
#define IDS_ERR_SEQ_PATH_EMPTY          5024
#define IDS_ERR_SEQ_ID_EMPTY            5025
#define IDS_ERR_SEQ_NAME_EMPTY          5026
#define IDS_ERR_PAS_CONTAINER_NULL      5027
#define IDS_ERR_PAS_LIST_EMPTY          5028
#define IDS_ERR_RESOURCE_PROTOCOL_FAILED 5029
#define IDS_ERR_INVALID_ENV_VAR_PASCOM_CONFIG 5030
#define IDS_ERR_INVALID_FILE_PATH       5031
#define IDS_COMMUNICATION_ERROR         5032
#define IDS_CHANNEL_CREATION            5033
#define IDS_SEQUENCE_REGISTRATION_FAILED 5034
#define IDS_APP_COMMUNICATION_ERROR     5035
#define IDS_ERR_UNKNOWN                 9999
#define IDS_INI_FILE_PATH_INVALID       10000
#define IDS_ERR_NULL_PTR                10001
#define IDS_TOSHIBA_DB_INVALID          10002
#define IDS_ERR_ACQORDER_EMPTY          10003
#define IDS_LABEL                       10004
#define IDS_ERR_SEQ_DELETE_FAIL         10005
#define IDS_ERR_SEQ_RENAME_FAIL         10006
#define IDS_ERR_SEQ_STORE_FAIL          10007
#define IDS_ERR_SEQ_PASTE_FAIL          10008
#define IDS_ERR_VAR_DATA                10009
#define IDS_ERR_PAS_LIST_EMPTY_NEW_LABEL 10010
#define IDS_ERR_PAS_RESTORE_FAIL        10011

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2000
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
