//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EPI.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORM_STATUS                 101
#define IDD_FORM_IMAGE_SELECT           102
#define IDR_EPIFORMVIEW_TMPL            103
#define IDD_PROPPAGE_EPI                107
#define IDR_MAINFRAME                   128
#define IDR_EPITYPE                     129
#define IDD_DIALOG_IMAGELIST            130
#define IDD_FORM_LEFT                   131
#define IDD_FORM_IMAGE_VIEWER           132
#define IDD_PROPPAGE_FSE                133
#define IDR_IMAGER_TOOLBAR              134
#define IDR_SLIDER_BAR                  144
#define IDD_DIALOG_OPEN_RAW             148
#define IDC_EDIT1                       1000
#define IDC_EDITSPIN                    1000
#define IDC_EDIT_EPI_SPIN               1000
#define IDC_EDIT_STATUS                 1000
#define IDC_EDITMERGE                   1000
#define IDC_EDIT_RAW_WIDHT              1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON_ZOOM_PLUS            1001
#define IDC_BUTTON_CLOSE                1001
#define IDC_BUTTON_RECON                1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_ZOOM_MINUS           1002
#define IDC_BUTTON_DISPLAY_DATA         1002
#define IDC_BUTTON3                     1003
#define IDC_BUTTON_MERGE_DATA           1003
#define IDC_BUTTON_CORRECT_PHASE        1004
#define IDC_LIST_IMAGE                  1007
#define IDC_LIST5                       1013
#define IDC_LIST_PROTOCOL               1013
#define IDC_COMBO3                      1014
#define IDC_BUTTON4                     1015
#define IDC_BUTTON_SEPARATE_RAW_DATA    1015
#define IDC_BUTTON6                     1017
#define IDC_BUTTON_DISPLAY_RAW          1017
#define IDC_RADIO2                      1019
#define IDC_RADIO_T2                    1019
#define IDC_RADIO3                      1020
#define IDC_RADIO_T1                    1020
#define IDC_STATIC_IMAGE_VIEW           1021
#define IDC_STATIC_RAW                  1021
#define IDC_STATIC_CONTROL1             1021
#define IDC_COMBO_DATAFORM              1022
#define IDC_RADIO1                      1023
#define IDC_RADIO_SPEEDER               1023
#define IDC_RADIO4                      1024
#define IDC_RADIO_NON_SPEEDER           1024
#define IDC_BUTTON_SEPAARTE_KSPACE      1025
#define IDC_CHECK_PROCESS               1026
#define IDC_CHECK_SHIFTPEAK             1028
#define IDC_CHECK_PC_METHOD             1029
#define IDC_RADIO_TIME_SHIFT            1030
#define IDC_RADIO_TS_LF                 1031
#define IDC_RADIO_TS_FREQ               1032
#define IDC_RADIO_DFT                   1033
#define IDC_RADIO_DIFFERENCE            1034
#define IDC_RADIO_ALLPC                 1035
#define IDC_RADIO_RELATIVE_PC           1036
#define IDC_STATIC_STUDY_FILE_NAME      1038
#define IDC_STATIC_PROCESS_SELECTION    1039
#define IDC_STATIC_PHASE_OPTIONS        1041
#define IDC_STATIC_SHIFT_PEAK_OPTIONS   1042
#define IDC_STATIC_PC_OPTIONS           1043
#define IDC_STATIC_KSPACE_SEPARATE      1047
#define IDC_COMBO_DATA_FORM             1048
#define IDC_COMBO_CHANNEL_SELECTION     1049
#define IDC_STATIC_DATA_FORM            1050
#define IDC_STATIC_CHANNEL_SELECTION    1051
#define IDC_STATIC_DISPLAY_OPTIONS      1052
#define IDC_STATIC_FRAME_DISPLAY        1053
#define IDC_STATIC_FRAME_ZOOM           1054
#define IDC_STATIC_PROCESSED            1055
#define IDC_STATIC_CONTROL2             1055
#define IDC_WINDOW_PROCESSED            1056
#define IDC_WINDOW_RAW                  1057
#define IDC_COMBO_DATA_FORM1            1058
#define IDC_CHECK1                      1063
#define IDC_STATIC_CONTROL3             1064
#define IDC_STATIC_CONTROL4             1065
#define IDC_LIST_RAW_DATA_PROTOCOL_LIST 1066
#define IDC_COMBO_RAW_DATA_FROM         1067
#define IDC_STATIC_EPI_DATA_FORM        1067
#define IDC_COMBO_EPI_DATA_FORM         1068
#define IDC_SPIN                        1069
#define IDC_STATIC_EPI_CHANNEL          1069
#define IDC_SPIN_CHANNEL                1070
#define IDC_STATIC_STEP_SELECTION       1071
#define IDC_COMBO_SELECT_STEP           1072
#define IDC_STATIC_IMAGE_INFO           1073
#define IDC_LIST_IMAGE_DATA_PROTOCOL_LIST 1075
#define IDC_STATIC_RECON                1075
#define IDC_LIST_STATUS                 1076
#define IDC_STATIC_STEP_SELECT          1077
#define IDC_STATIC_RAW_IMAGE_TYPE       1078
#define IDC_STATIC_RAW_WIDHT            1079
#define IDC_STATIC_RAW_HEIGHT           1080
#define IDC_COMBO_RAW_TYPE              1081
#define IDC_EDIT_RAW_HEIGHT             1082
#define IDC_STATIC_RAW_FORM             1083
#define IDC_COMBO_RAW_FORM              1084
#define ID_BUTTON_1x1                   32772
#define ID_BUTTON_1x2                   32773
#define ID_BUTTON_2x2                   32774
#define ID_BUTTON_RESETIMAGE            32775
#define ID_BUTTON_FITIMAGE              32777
#define ID_VIEW_SLIDERBAR               32778
#define ID_DUMMY1                       32784
#define ID_DUMMY2                       32785
#define ID_DUMMY3                       32786
#define ID_DUMMY4                       32787
#define ID_DUMMY5                       32788
#define ID_DUMMY6                       32789
#define ID_DUMMY7                       32790
#define ID_DUMMY8                       32791
#define ID_DUMMY9                       32792
#define ID_DUMMY10                      32793
#define ID_DUMMY11                      32794
#define ID_DUMMY12                      32795
#define ID_DUMMY13                      32796
#define ID_DUMMY14                      32797
#define ID_DUMMY15                      32798
#define ID_DUMMY16                      32799
#define ID_DUMMY17                      32800
#define ID_DUMMY18                      32801
#define ID_DUMMY19                      32802
#define ID_EDIT_WW                      32803
#define ID_EDIT_WL                      32804
#define ID_EDIT_ROTZ                    32805
#define ID_SLIDE_WW                     32806
#define ID_SLIDE_WL                     32807
#define ID_SLIDE_ROTZ                   32808
#define ID_SPIN_WW                      32809
#define ID_SPIN_WL                      32810
#define ID_SPIN_ROTZ                    32811
#define ID_BUTTON32812                  32812
#define ID_STATIC_WW                    32813
#define ID_STATIC_WL                    32814
#define ID_VIEW_IMAGERTOOLS             32815
#define ID_VIEW_WWWLTOOLBAR             32816
#define ID_VIEW_IMAGER                  32817
#define ID_VIEW_WWWL                    32818
#define ID_BUTTON_OPENIMAGE             32819
#define ID_DIRECTORY_SELECT             32820
#define ID_BUTTON_REFRESH               32832
#define ID_BUTTON32836                  32836
#define ID_BUTTON_OPEN_RAW              32837
#define ID_INDICATOR_INITIAL_DIR        61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
