/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User.Interface.SupplierEnterpriseAdminRole;

import Business.Enterprise.SupplierEnterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asha
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private SupplierEnterprise supplierEnterprise;
    public ManageOrganizationJPanel(JPanel userProcessContainer,SupplierEnterprise supplierEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierEnterprise = supplierEnterprise;
         Color c = new Color(0, 85, 119);
        this.setBackground(c);
        populateOrganizationTable();
        populateOrganizationTypeComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orgTypejComboBox = new javax.swing.JComboBox();
        backjButton = new javax.swing.JButton();
        addOrgjButton = new javax.swing.JButton();
        titlejLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        organizationNamejTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 85, 119));
        setForeground(new java.awt.Color(255, 255, 255));

        organizationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Id", "Organization type"
            }
        ));
        jScrollPane1.setViewportView(organizationjTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Organization");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Organization Type");

        orgTypejComboBox.setBackground(new java.awt.Color(120, 120, 120));
        orgTypejComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orgTypejComboBox.setForeground(new java.awt.Color(255, 255, 255));

        backjButton.setBackground(new java.awt.Color(30, 30, 30));
        backjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backjButton.setForeground(new java.awt.Color(255, 255, 255));
        backjButton.setText("<< Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        addOrgjButton.setBackground(new java.awt.Color(30, 30, 30));
        addOrgjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addOrgjButton.setForeground(new java.awt.Color(255, 255, 255));
        addOrgjButton.setText("Add Organization");
        addOrgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgjButtonActionPerformed(evt);
            }
        });

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(255, 255, 255));
        titlejLabel.setText("Supplier Admin - Manage Organization");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Organization Name");

        organizationNamejTextField.setBackground(new java.awt.Color(120, 120, 120));
        organizationNamejTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        organizationNamejTextField.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(backjButton))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(orgTypejComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                                    .addComponent(addOrgjButton)
                                    .addComponent(organizationNamejTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(titlejLabel)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titlejLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(orgTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organizationNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(addOrgjButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addOrgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgjButtonActionPerformed
        // TODO add your handling code here:
        Type type = (Type)orgTypejComboBox.getSelectedItem();
        if(null == type){
            //pending
            return;
        }
        String orgName = organizationNamejTextField.getText();
        if((null == orgName) || (true == orgName.isEmpty())){
            JOptionPane.showMessageDialog(this, "Please enter a valid organization name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        supplierEnterprise.getOrganizationDirectory().createOrganization(type,orgName);
        populateOrganizationTable();
    }//GEN-LAST:event_addOrgjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrgjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox orgTypejComboBox;
    private javax.swing.JTextField organizationNamejTextField;
    private javax.swing.JTable organizationjTable;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables

    private void populateOrganizationTable() {        
        DefaultTableModel model = (DefaultTableModel) organizationjTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : supplierEnterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getOrganizationName();
            
            model.addRow(row);
        }
    }

    private void populateOrganizationTypeComboBox() {
        orgTypejComboBox.removeAllItems();
        for (Type type : Organization.Type.values()){
            if (type.getValue().startsWith("Supplier"))
                orgTypejComboBox.addItem(type);
        }
    }
}
