/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package User.Interface.SystemAdminRole;
import Bsuiness.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asha
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;
 Color c = new Color(0, 85, 119);
        this.setBackground(c);
        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();
        model.setRowCount(0);
        
        if(0 >= system.getNetworkList().size()){
            //pending status
            return;
        }
        
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        networkNamejLabel = new javax.swing.JLabel();
        addNetworkJButton = new javax.swing.JButton();
        networkNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        titlejLabel = new javax.swing.JLabel();
        addNetworkjLabel = new javax.swing.JLabel();
        deleteNetworkjButton = new javax.swing.JButton();
        deleteNetworkjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 85, 119));
        setForeground(new java.awt.Color(255, 255, 255));

        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Netwrok Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);
        if (networkJTable.getColumnModel().getColumnCount() > 0) {
            networkJTable.getColumnModel().getColumn(0).setResizable(false);
        }

        networkNamejLabel.setText("Network Name");

        addNetworkJButton.setText("Add Network");
        addNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNetworkJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel.setText("System Admin - Manage Networks");

        addNetworkjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addNetworkjLabel.setText("Add Network");

        deleteNetworkjButton.setText("Delete Network");
        deleteNetworkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNetworkjButtonActionPerformed(evt);
            }
        });

        deleteNetworkjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteNetworkjLabel.setText("Delete Network");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(titlejLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addNetworkJButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(networkNamejLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(networkNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addNetworkjLabel)
                                    .addComponent(backJButton)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deleteNetworkjButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteNetworkjLabel, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addNetworkJButton, deleteNetworkjButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titlejLabel)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNetworkjLabel)
                    .addComponent(deleteNetworkjLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkNamejLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNetworkJButton)
                    .addComponent(deleteNetworkjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addNetworkJButton, deleteNetworkjButton});

    }// </editor-fold>//GEN-END:initComponents

    private void addNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNetworkJButtonActionPerformed

        //read the network name
        String networkName = networkNameJTextField.getText();
        if((null == networkName) || (true == networkName.isEmpty())){
            JOptionPane.showMessageDialog(this, "Please enter a valid network name", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //create and add a new network
        Network network = system.createAndAddNetwork(networkName);
        if(null == network){
            JOptionPane.showMessageDialog(this, "An error occurred! ", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }      

        populateNetworkTable();
    }//GEN-LAST:event_addNetworkJButtonActionPerformed

    private void deleteNetworkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNetworkjButtonActionPerformed
        // TODO add your handling code here:
        //get the selected network from the table
        int networkCount = system.getNetworkList().size();
        if (1 > networkCount) {
            JOptionPane.showMessageDialog(this, "No networks available to delete.", "Error",JOptionPane.WARNING_MESSAGE);
            return;
        }

        int selectedRow = networkJTable.getSelectedRow();
        if (0 > selectedRow) {
            JOptionPane.showMessageDialog(this, "Please select a network from the list.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Network  l_network = (Network) networkJTable.getValueAt(selectedRow, 0);
        if(null == l_network){
            //pending status
            return;
        }
        system.deleteNetwork(l_network);
        populateNetworkTable();        
    }//GEN-LAST:event_deleteNetworkjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNetworkJButton;
    private javax.swing.JLabel addNetworkjLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteNetworkjButton;
    private javax.swing.JLabel deleteNetworkjLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkJTable;
    private javax.swing.JTextField networkNameJTextField;
    private javax.swing.JLabel networkNamejLabel;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
