//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PQM.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PQM_DIALOG                  101
#define IDD_MRSPRESCANDLG_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDR_PQMTYPE                     129
#define IDB_MODE_BITMAP1                130
#define IDD_ANATOMY                     130
#define IDB_MODE_BITMAP2                131
#define IDD_COMMENT                     131
#define IDB_MODE_BITMAP3                132
#define IDD_COMPASS_LOCATION_DEBUG      132
#define IDB_MODE_BITMAP4                133
#define IDB_MODE_BITMAP5                134
#define IDD_CFA                         134
#define IDI_ADD_BUTTON_IMAGE            135
#define IDI_DELETE_BUTTON_IMAGE         136
#define IDB_DUMMY_BUTTON1_IMAGE         137
#define IDR_MENU_AUTO_VOICE             137
#define IDB_CLOSE_BUTTON_IMAGE          138
#define IDR_PQM_ACCELERATOR             138
#define IDD_SET_SCAN_OFFSET             138
#define IDB_PAUSE_BUTTON_IMAGE          140
#define IDB_RESUME_BUTTON_IMAGE         141
#define IDI_UTILITY_BUTTON_IMAGE        142
#define IDD_DLG_GATE                    142
#define IDB_LOCATOR_BUTTON_IMAGE        143
#define IDB_INJECTTIME_BUTTON_IMAGE     144
#define IDR_MENU_CFA                    144
#define IDI_SCANEDIT_BUTTON_IMAGE       145
#define IDD_DLG_COIL                    145
#define IDI_PASS_BUTTON_IMAGE           146
#define IDB_BITMAP_B_ABDOMEN            157
#define IDB_BITMAP_S_ABDOMEN            158
#define IDB_BITMAP_B_CHEST              159
#define IDB_BITMAP_S_CHEST              160
#define IDB_BITMAP_B_PELVIS             161
#define IDB_BITMAP_S_PELVIS             162
#define IDB_BITMAP_B_TLSPINE            163
#define IDB_BITMAP_S_TLSPINE            164
#define IDB_BITMAP_B_SHOULDER           165
#define IDB_BITMAP_S_SHOULDER           166
#define IDB_BITMAP_B_HEAD               167
#define IDR_PROTOCOL_MENU               167
#define IDB_BITMAP_S_HEAD               168
#define IDR_CONTRAST_AGENT_MENU         168
#define IDB_BITMAP_B_CSPINE             169
#define IDB_BITMAP_S_CSPINE             170
#define IDB_BITMAP_B_EXTREMITY          171
#define IDB_BITMAP_S_EXTREMITY          172
#define IDB_BITMAP_B_EXTREMITY2         173
#define IDB_BITMAP_S_EXTREMITY2         174
#define IDB_BITMAP_B_HAND               175
#define IDB_BITMAP_S_HAND               176
#define IDB_BITMAP_B_ANKLE              177
#define IDB_BITMAP_S_ANKLE              178
#define IDB_BITMAP_CFA_LEFT             191
#define IDD_PATIENT_ORIENTATION_DIALOG  191
#define IDB_BITMAP_CFA_RIGHT            192
#define IDD_PQM_QUEUE_DIALOG            195
#define IDR_ORIENTATION1_MENU           196
#define IDR_ORIENTATION2_MENU           197
#define IDB_UNCHECK_RADIO               198
#define IDR_ORIENTATION3_MENU           198
#define IDB_BITMAP_JINTAI               204
#define IDR_UTILITY_MENU                205
#define IDB_STATUS_CURRENT_ENABLE_BITMAP 212
#define IDB_STATUS_CURRENT_DISABLE_BITMAP 213
#define IDD_INFO_SEQ                    215
#define IDD_GATING_DIALOG               217
#define IDB_BITMAP_SAR_ABDOMEN          219
#define IDB_BITMAP_SAR_ANKLE            220
#define IDB_BITMAP_SAR_CHEST            221
#define IDB_BITMAP_SAR_CSPINE           222
#define IDB_BITMAP_SAR_EXTREMITY2       223
#define IDB_BITMAP_SAR_EXTREMITY        224
#define IDB_BITMAP_SAR_HAND             225
#define IDB_BITMAP_SAR_HEAD             226
#define IDB_BITMAP_SAR_PELVIS           227
#define IDB_BITMAP_SAR_SHOULDER         228
#define IDB_BITMAP_SAR_TLSPINE          229
#define IDB_GRP1_COMBO11_BITMAP         230
#define IDB_GRP1_COMBO12_BITMAP         231
#define IDB_GRP1_COMBO23_BITMAP         234
#define IDB_GRP1_COMBO31_BITMAP         236
#define IDB_GRP1_COMBO32_BITMAP         237
#define IDB_GRP11_BITMAP                238
#define IDB_GRP12_BITMAP                239
#define IDB_GRP13_BITMAP                240
#define IDB_GRP14_BITMAP                241
#define IDB_GRP15_BITMAP                242
#define IDB_GRP16_BITMAP                243
#define IDB_GRP17_BITMAP                244
#define IDB_GRP18_BITMAP                245
#define IDB_GRP2_COMBO11_BITMAP         246
#define IDB_GRP2_COMBO12_BITMAP         247
#define IDB_GRP2_COMBO21_BITMAP         248
#define IDB_GRP2_COMBO22_BITMAP         249
#define IDB_GRP2_COMBO23_BITMAP         250
#define IDB_GRP2_COMBO24_BITMAP         251
#define IDB_GRP2_COMBO31_BITMAP         252
#define IDB_GRP2_COMBO32_BITMAP         253
#define IDB_GRP21_BITMAP                254
#define IDB_GRP22_BITMAP                255
#define IDB_GRP23_BITMAP                256
#define IDB_GRP24_BITMAP                257
#define IDB_GRP25_BITMAP                258
#define IDB_GRP26_BITMAP                259
#define IDB_GRP27_BITMAP                260
#define IDB_GRP28_BITMAP                261
#define IDB_PQM_BITMAP                  262
#define IDB_SCAN_ANATOMY_BITMAP         263
#define IDI_DONE_ICON                   264
#define IDI_DISABLED_ICON               265
#define IDI_CURRENT_ICON                266
#define IDI_FAIL_ICON                   267
#define IDI_WAIT_ICON                   268
#define IDD_PQMMANUALPRESCAN_DIALOG     269
#define IDB_PQMLIST_CTRL_AREA__BITMAP   272
#define IDB_PATIENT_ORIENTATION_BITMAP_BITMAP 273
#define IDD_CAUTION_DBDT                273
#define IDD_COIL_SELECTION_WINDOW_LEFT  274
#define IDB_BITMAP_CAUTION              274
#define IDD_COIL_SELECTION_WINDOW_RIGHT 275
#define IDB_BITMAP_AXISLOCATOR_LEFT     276
#define IDB_BITMAP_AXISLOCATOR_RIGHT    277
#define IDB_BITMAP_COILLIST             278
#define IDB_BITMAP_COIL_LISTSEL         279
#define IDB_BITMAP_SPINE_LEFT           280
#define IDB_BITMAP_SPINE_RIGHT          281
#define IDB_BITMAP_MOVE_FREE_LEFT       282
#define IDB_BITMAP_MOVE_FREE_RIGHT      283
#define IDD_DIALOG_COIL_LST             284
#define IDB_BITMAP_SPINE_LEFT_RIGHTDIALOG 285
#define IDB_BITMAP_SPINE_RIGHT_RIGHTDIALOG 286
#define IDB_PLANNEDPROTOCOL_IMAGE       287
#define IDB_CAUTION_DBDT_BITMAP         288
#define IDB_BITMAP_SPINE_MIDDLE_DIALOG  289
#define IDB_PLAN_ACTIVE_BITMAP          290
#define IDI_AUTO_SCAN_ICON              291
#define IDI_DONE_PROTOCOL_ICON          292
#define IDI_FAIL_PROTOCOL_ICON          293
#define IDI_CURRENT_PROTOCOL_ICON       294
#define IDI_INJECTOR_ACTIVE             295
#define IDI_INJECTOR_DISABLE_NO_FUNCTION 296
#define IDI_INJECTOR_DISABLE            297
#define IDI_VOICE_ACTIVE                298
#define IDI_VOICE_DISABLE_NO_FUNCTION   299
#define IDI_VOICE_DISABLE               300
#define IDI_PLAN_ACTIVE_ICON            301
#define IDI_PLAN_CONE_WAIT_PROTOCOL_ICON 302
#define IDI_PLAN_CONE_NON_WAIT_PROTOCOL_ICON 303
#define IDB_MODE_BITMAP_DISABLED_NO_FUNCTION_2 304
#define IDB_MODE_BITMAP_DISABLED_NO_FUNCTION_3 305
#define IDI_SCANOFFSET_BUTTON_IMAGE     306
#define IDB_SAR_REGION_UNSELECT         307
#define IDR_SFT_MENU                    308
#define IDI_PAUSE_PROTOCOL_ICON         309
#define IDD_PLANDUP_DIALOG              334
#define IDD_PQMDEBUG_DIALOG             335
#define IDD_COMPASS_SETTING_DIALOG      336
#define IDB_ARROW_DOWN                  337
#define IDB_ARROW_UP                    338
#define IDI_MOVEBED_DISABLED            356
#define IDI_MOVEBED_ACTIVE              357
#define IDI_MOVEBED_NORMAL              358
#define IDR_MENU_COUCH                  359
#define IDD_SCAN_COMMENT_XML_DIALOG     360
#define IDR_SCAN_ID_MENU                361
#define IDD_PASSWORD_DLG                362
#define IDB_MOVE_COUCH_LEFT             363
#define IDD_SCANOFFSET_DIALOG           364
#define IDB_IMAGE_OFFSET_HUMAN          364
#define IDB_MOVE_COUCH_LEFT_BUTTON_BITMAP 365
#define IDB_MOVE_COUCH_RIGHT_BUTTON_BITMAP 366
#define IDB_MOVE_COUCH_CENTER_BITMAP    369
#define IDB_MOVE_COUCH_RIGHT            370
#define IDB_SCAN_OFFSET_ORI_LEFT_BACK   371
#define IDB_SCAN_OFFSET_ORI_LEFT_DOWN   372
#define IDB_SCAN_OFFSET_ORI_LEFT_FRONT  373
#define IDB_SCAN_OFFSET_ORI_LEFT_UP     374
#define IDB_SCAN_OFFSET_ORI_RIGHT_BACK  375
#define IDB_SCAN_OFFSET_ORI_RIGHT_DOWN  376
#define IDB_SCAN_OFFSET_ORI_RIGHT_FRONT 377
#define IDB_SCAN_OFFSET_ORI_RIGHT_UP    378
#define IDD_DELAY                       379
#define IDR_COIL_CHANNEL_MODE           388
#define IDD_WIRELESS_GATING_DIALOG      389
#define IDI_WAIT_FOR_AUTO_SCAN          390
#define IDR_MENU_PLAN_MASTER_SLAVE      391
#define IDD_AMB_DIALOG                  392
#define IDI_ICON_6MIN_NOWAIT            393
#define IDI_ICON_6MIN_WAIT              394
#define IDI_ICON_10SEC                  395
#define IDI_ICON_AUTOSCAN_6MIN_NOWAIT   396
#define IDI_ICON_AUTOSCAN_6MIN_WAIT     397
#define IDI_ICON_AUTOSCAN_10SEC         398
#define IDI_ICON_AUTOSCAN_SAE           399
#define IDI_ICON_SAE                    400
#define IDC_SCAN_OFFSET_STATIC          1000
#define IDC_COIL_INFO_STATIC            1001
#define IDC_PARAM1_UP                   1001
#define IDC_LIST_SEQ                    1001
#define IDC_MOVE_COUCH_LEFT             1001
#define IDC_SAR_SCAN_ANATOMY_RGN_BUTTON 1002
#define IDC_PARAM1_DOWN                 1002
#define IDC_LIST_CONT                   1002
#define IDC_IMAGE_OFFSET                1002
#define IDC_SCAN_ANATOMY_STATIC         1003
#define IDC_PARAM2_DOWN                 1003
#define IDC_LIST_OPT                    1003
#define IDC_END_EXQAM                   1004
#define IDC_PARAM2_UP                   1004
#define IDC_COMM_VALUE                  1004
#define IDC_ORIENTATION_OPTION_1        1005
#define IDC_REMAINING_TIME_STATIC       1005
#define IDC_EDIT_PARAM1                 1005
#define IDC_ABORT                       1006
#define IDC_EDIT_PARAM2                 1006
#define IDC_ORIENTATION_OPTION_2        1007
#define IDC_SAR_ANATOMY_STATIC2         1007
#define IDC_SLIDER_PARAM1               1007
#define IDC_CLOSE                       1008
#define IDC_SLIDER_PARAM2               1008
#define IDC_ORIENTATION_OPTION_3        1009
#define IDC_FRAM_1                      1009
#define IDC_BUTTON_CLOSE                1010
#define IDC_FRAM_2                      1010
#define IDC_PATIENT_ORIENTATION_MAIN_IMAGE_STATIC 1011
#define IDC_GET_INTERVAL                1012
#define IDC_MIN_PARAM1                  1012
#define IDC_MOVE_COUCH_WND              1012
#define IDC_PAUSE_RESUME                1013
#define IDC_MIN_PARAM2                  1013
#define IDC_SCAN_START                  1014
#define IDC_MAX_PARAM1                  1014
#define IDC_QUEUE_AND_NEXT              1015
#define IDC_MAX_PARAM2                  1015
#define IDC_MAIN_STATIC_FRAME           1016
#define IDC_COILPORT_1                  1016
#define IDC_NEXT_AND_COPY               1017
#define IDC_COILPORT_2                  1017
#define IDC_UTILITY_BUTTON              1018
#define IDC_COILPORT_3                  1018
#define IDC_RESET                       1019
#define IDC_COILPORT_4                  1019
#define IDC_PASS_BUTTON                 1020
#define IDC_COILPORT_5                  1020
#define IDC_CANCEL                      1021
#define IDC_COILPORT_6                  1021
#define IDC_SCAN_EDIT_BUTTON            1022
#define IDC_COILPORT_7                  1022
#define IDC_INJECT_TIME_BUTTON          1023
#define IDC_COILPORT_8                  1023
#define IDC_LOCATOR_BUTTON              1024
#define IDC_COILPORT_9                  1024
#define IDC_DUPLICATE_BUTTON            1025
#define IDC_COIL_LOCATION_1             1025
#define IDC_DELETE_BUTTON               1026
#define IDC_STATIC_LABEL_PORT           1027
#define IDC_SCAN_OFFSET_BUTTON          1028
#define IDC_STATIC_LABEL_NAME           1029
#define IDC_EDIT_COMMENT                1030
#define IDC_COIL_BUTTON                 1031
#define IDC_STATIC_LABEL_ID             1032
#define IDC_EDIT_ID                     1033
#define IDC_PQM_SEQ_LISTCTRL            1034
#define IDC_COILPORT_10                 1035
#define IDC_STATIC_LABEL_COMMENT        1037
#define IDC_COILPORT_11                 1037
#define IDC_COILPORT_12                 1039
#define IDC_COILPORT_13                 1041
#define IDC_EDIT_SCAN_OFFSET_Y          1042
#define IDC_COIL_LOCATION_2             1043
#define IDC_EDIT_SCAN_OFFSET_Z          1044
#define IDC_COIL_LOCATION_3             1044
#define IDC_BUTTON_INCR_Z               1045
#define IDC_COIL_LOCATION_4             1045
#define IDC_BUTTON_CFA_LEFT             1046
#define IDC_COIL_LOCATION_5             1046
#define IDC_COIL_LOCATION_6             1047
#define IDC_SEQ_INFO_LIST               1048
#define IDC_COIL_LOCATION_7             1048
#define IDC_GATESOURCECOMBO             1049
#define IDC_COIL_LOCATION_8             1049
#define IDC_DISPLAY_GATE_PLAN_WINDOW    1050
#define IDC_COIL_LOCATION_9             1050
#define IDC_RR_INTERVAL                 1051
#define IDC_COIL_DETECTFLAG_1           1051
#define IDC_HEARTBEAT                   1052
#define IDC_COIL_DETECTFLAG_2           1052
#define IDC_PPINTERVAL                  1053
#define IDC_COIL_DETECTFLAG_3           1053
#define IDC_RRINTERVAL                  1054
#define IDC_COIL_DETECTFLAG_4           1054
#define IDC_COIL_DETECTFLAG_5           1055
#define IDC_EDIT_SCAN_OFFSET_X          1056
#define IDC_COIL_DETECTFLAG_6           1056
#define IDC_COIL_DETECTFLAG_7           1057
#define IDC_COIL_DETECTFLAG_8           1058
#define IDC_BUTTON_APPLY                1059
#define IDC_COIL_DETECTFLAG_9           1059
#define IDC_STATIC_EXCITATIONN_SELECTION 1060
#define IDC_COIL_LOCATION_10            1060
#define IDC_RADIO_BUTTON_WATER          1061
#define IDC_COIL_DETECTFLAG_10          1061
#define IDC_RADIO_BUTTON_FAT            1062
#define IDC_COIL_LOCATION_11            1062
#define IDC_BUTTON_CFA_RETRY            1063
#define IDC_COIL_DETECTFLAG_11          1063
#define IDC_EDIT_CFA                    1064
#define IDC_COIL_LOCATION_12            1064
#define IDC_BUTTON_CFA_RIGHT            1065
#define IDC_COIL_DETECTFLAG_12          1065
#define IDC_STATIC_ANATOMY              1066
#define IDC_COIL_LOCATION_13            1066
#define IDC_LIST_COIL                   1067
#define IDC_COIL_DETECTFLAG_13          1067
#define IDC_LIST_GATE                   1068
#define IDC_STATIC_LEBEL_ID             1069
#define IDC_BUTTON_DECR_Z               1073
#define IDC_STATIC_CHEST_BUTTON         1074
#define IDC_STATIC_ABDOMEN_BUTTON       1075
#define IDC_STATIC_PELVIS_BUTTON        1076
#define IDC_STATIC_SHOULDER_BUTTON      1077
#define IDC_STATIC_EXTREMITY_BUTTON     1078
#define IDC_STATIC_EXTREMITY2_BUTTON    1079
#define IDC_STATIC_HAND_BUTTON          1080
#define IDC_STATIC_ANKLE_BUTTON         1081
#define IDC_STATIC_HEAD_BUTTON          1082
#define IDC_STATIC_TLSPINE_BUTTON       1083
#define IDC_STATIC_CSPINE_BUTTON        1084
#define IDC_GATE_SOURCE_STATIC_FRAME    1085
#define IDC_GATE_SOURCE_STATIC          1086
#define IDC_EXIT_STATIC_FRAME_STATIC    1087
#define IDC_HEART_BEAT_STATIC           1088
#define IDC_GATING_INTERVAL_STATIC      1089
#define IDC_GATING_PLAN_DIALOG_STATIC_FRAME 1090
#define IDC_CFA_STATIC_GRAPH            1091
#define IDC_UTILITY                     1092
#define IDC_AXISLOCATOR                 1092
#define IDC_MRSSCAN_LISTCTRL            1098
#define IDC_START_BUTTON                1099
#define IDC_ABORT_BUTTON                1100
#define IDC_MRSDIALOG_ADJ_CENTER_FREQ_CHECK 1101
#define IDC_MRSDIALOG_START_BUTTON      1102
#define IDC_MRSDIALOG_WATER_SIGNAL_REF_CHECK 1103
#define IDC_RXCOIL_STATIC               1104
#define IDC_RFL_STATIC                  1105
#define IDC_CFA_STATIC                  1106
#define IDC_RXGAIN_STATIC               1107
#define IDC_VAPTHROUGH_STATIC           1108
#define IDC_RFL_GAIN_EDIT               1109
#define IDC_RFL_SCALE_EDIT              1110
#define IDC_BUTTON_FCOIL_LEFT           1110
#define IDC_CFA_FSYVALUE_EDIT           1111
#define IDC_BUTTON_FCOIL_RIGHT          1111
#define IDC_RXGAIN_RGNVALUE_EDIT        1112
#define IDC_TXCOIL_COMBO                1113
#define IDC_BUTTON_SCOIL_RIGHT          1113
#define IDC_RXCOIL_COMBO                1114
#define IDC_BUTTON_INVOKE_COIL          1114
#define IDC_RFL_COMBO                   1115
#define IDC_CFA_COMBO                   1116
#define IDC_RXGAIN_COMBO                1117
#define IDC_VAPTHROUGH_COMBO            1118
#define IDC_RFL_OPTION_COMBO            1119
#define IDC_CFA_OPTION_COMBO            1120
#define IDC_RXGAIN_OPTION_COMBO         1121
#define IDC_TXCOIL_STATIC               1122
#define IDC_PRESCAN_MAIN_STATIC_FRAME   1123
#define IDC_QUEUE_AND_EXIT              1124
#define IDC_BUTTON_PORT_1               1125
#define IDC_PASSWD                      1125
#define IDC_BUTTON_PORT_2               1126
#define IDC_ERROR                       1126
#define IDC_ERROR_DBDT                  1126
#define IDC_BUTTON_PORT_3               1127
#define IDC_STATIC_DBDT                 1127
#define IDC_BUTTON_PORT_4               1128
#define IDC_STATIC_DBDT_PWD             1128
#define IDC_BUTTON_PORT_5               1129
#define IDC_OK                          1129
#define IDC_BUTTON_PORT_6               1130
#define IDC_BUTTON_PORT_7               1131
#define IDC_BUTTON_SCOIL_LEFT           1165
#define IDC_BUTTON_L1                   1166
#define IDC_BUTTON_L2                   1167
#define IDC_BUTTON_LBL_L2               1168
#define IDC_BUTTON_LBL_L3               1169
#define IDC_BUTTON_LBL_G                1170
#define IDC_BUTTON_LBL_A1               1171
#define IDC_BUTTON_LBL_A2               1172
#define IDC_BUTTON_LBL_A3               1173
#define IDC_BUTTON_COIL_1               1173
#define IDC_BUTTON_LBL_A4               1174
#define IDC_BUTTON_COIL_2               1174
#define IDC_BUTTON_LBL_A5               1175
#define IDC_BUTTON_COIL_3               1175
#define IDC_BUTTON_LBL_A6               1176
#define IDC_BUTTON_COIL_4               1176
#define IDC_BUTTON_LBL_A7               1177
#define IDC_BUTTON_COIL_5               1177
#define IDC_BUTTON_COIL_6               1178
#define IDC_BUTTON_COIL_7               1179
#define IDC_BUTTON_COIL_8               1180
#define IDC_BUTTON_COIL_9               1181
#define IDC_BUTTON_COIL_10              1182
#define IDC_BUTTON_POS_1                1184
#define IDC_BUTTON_POS_2                1185
#define IDC_BUTTON_POS_3                1186
#define IDC_BUTTON_POS_4                1187
#define IDC_BUTTON_POS_5                1188
#define IDC_BUTTON_POS_6                1189
#define IDC_BUTTON_POS_7                1190
#define IDC_BUTTON_POS_8                1191
#define IDC_BUTTON_POS_9                1192
#define IDC_STATIC1                     1193
#define IDC_STATIC2                     1194
#define IDC_STATIC3                     1195
#define IDC_STATIC4                     1196
#define IDC_STATIC5                     1197
#define IDC_STATIC6                     1198
#define IDC_STATIC7                     1199
#define IDC_STATIC8                     1200
#define IDC_STATIC9                     1201
#define IDC_STATIC10                    1202
#define IDC_LIST_PORT                   1203
#define IDC_EDIT_MSG                    1204
#define IDS_STATIC_CHEST                1205
#define IDS_STATIC_ABDOMEN              1206
#define IDS_STATIC_PELVIS               1207
#define IDS_STATIC_SHOULDER             1208
#define IDS_STATIC_EXTREMITY            1209
#define IDS_STATIC_EXTREMITY2           1210
#define IDS_STATIC_HAND                 1211
#define IDS_STATIC_ANKLE                1212
#define IDS_STATIC_HEAD                 1213
#define IDS_STATIC_TLSPINE              1214
#define IDS_COIL_PORT                   1215
#define IDS_COIL_NAME                   1216
#define IDS_COIL_ID                     1217
#define IDS_GATE_GRS                    1218
#define IDS_GATE_MIN_GRS                1219
#define IDS_GATE_MAX_GRS                1220
#define IDS_LESS_THAN_MIN               1221
#define IDS_MORE_THAN_MAX               1222
#define IDS_ERR_VIEW_PTR                1223
#define IDS_ERR_SEQ_PTR                 1224
#define IDS_PQM_LABEL_STATUS_AUTO       1225
#define IDS_PQM_LABEL_STATUS_BREATH     1226
#define IDS_PQM_LABEL_STATUS_COUCH      1227
#define IDS_ERR_ANATOMY_DLG_PTR         1228
#define IDS_ERR_COIL_PTR                1229
#define IDS_INVALID_INPUT               1230
#define IDS_RES_MEM_GUI_INFO_SEQ_TITLE  1231
#define IDS_MAX_PROTOCOL                1232
#define IDS_ERR_CLIENT_CONNECTION       1233
#define IDS_ERR_LOGFILE                 1234
#define IDS_ERR_DLLFAILED               1235
#define IDS_PQM_LABEL_STATUS_WAIT       1236
#define IDS_PQM_LABEL_STATUS_CURRENT    1237
#define IDS_PQM_LABEL_STATUS_SUCCESS    1238
#define IDS_PQM_LABEL_STATUS_FAIL       1239
#define IDS_APC_START                   1240
#define IDS_SCAN_START                  1241
#define IDS_ERR_INITIALIZED             1242
#define IDS_STUDY_NOT_FOUND             1243
#define IDS_NO_PROTOCOL                 1244
#define IDS_STATIC_CSPINE               1245
#define IDS_ERR_NO_COIL_IN_PORT         1246
#define IDS_PQM_WARN_PRESCAN_COUCH      1247
#define IDS_PQM_WARN_PRESCAN_DIFF_COIL  1248
#define IDS_PQM_WARN_PRESCAN_SPEEDER_COIL 1249
#define IDS_ERR_REQ                     1250
#define IDS_REPLY_ERR                   1251
#define IDS_ERR_ACC_PRESCAN             1252
#define IDS_ERR_ACQMAN_ACQINFO          1253
#define IDS_ERR_ACQMAN_ACQINFO_DONE     1254
#define IDS_ERR_ACQMAN_RFINTERLOCK      1255
#define IDS_ERR_ACQMAN_RFINTERLOCK_DONE 1256
#define IDS_ERR_ACQMAN_PRESCAN          1257
#define IDS_ERR_ACQMAN_PRESCAN_DONE     1258
#define IDS_ERR_ACQMAN_PRESCAN_CONTINUE 1259
#define IDS_ERR_ACQMAN_PRESCAN_CONTINUE_DONE 1260
#define IDS_ERR_ACQMAN_ACQUISITION      1261
#define IDS_ERR_ACQMAN_ACQUISITION_DONE 1262
#define IDS_ERR_ACQMAN_ACQUISITION_CONTINUE 1263
#define IDS_ERR_ACQMAN_ACQUISITION_CONTINUE_DONE 1264
#define IDS_ERR_CONNECT_ACQMAN          1265
#define IDS_ERR_INITIALIZE_LISTENER_ACQMAN 1266
#define IDS_COM_INIT_FAIL               1267
#define IDS_NO_READ_VALUE               1268
#define IDS_ERR_MSG_NOT_SENT            1269
#define IDS_NO_FUNC_BIT                 1270
#define IDS_ERR_NO_COILDB               1271
#define IDS_COIL_INFO_ABSENT            1272
#define IDS_CANNOT_PROCEED              1273
#define IDS_NOCOIL                      1274
#define IDS_NOSENDMESSAGE               1275
#define IDS_COIL_GR_FAIL                1276
#define IDS_COIL_GET_ERR                1277
#define IDS_INTERLOCK_ERROR             1278
#define IDS_CANNOT_RESPOND              1279
#define IDS_MISC_ERR                    1280
#define IDS_ERR_ILLEGAL_COIL_CONNECT    1281
#define IDS_PQM_WARN_SCAN_DRKS_RECON_MODE 1282
#define IDS_DUP_STUDYID                 1283
#define IDS_NO_SHARE_MEM                1284
#define IDS_ERR_OCCURRED                1285
#define IDS_ERR_SOCKET_CLOSE            1286
#define IDS_ERR_SOCKET                  1287
#define IDS_MAXPROTOCOL                 1288
#define IDS_ERR_XMLFILE_LOADING_FAILED  1289
#define IDS_TRACELOGFLAG                1290
#define IDS_TRACELOGPATH                1291
#define IDS_EVENTLOGFLAG                1292
#define IDS_EVENTLOGPATH                1293
#define IDS_ERR_ACQMAN_SHIMCTRL         1294
#define IDS_ERR_ACQMAN_SHIMCTRL_DONE    1295
#define IDS_ERR_ACQMAN_GATEMODE         1296
#define IDS_ERR_ACQMAN_GATEMODE_DONE    1297
#define IDS_PQM_SAR_ERROR               1298
#define IDS_PQM_SAR_OK_BUT_COIL         1299
#define IDS_PQM_SAR_OK_BUT_SAR          1300
#define IDS_WARN_SCAN_MULTI_COVERAGES   1301
#define IDS_WARN_SCAN_PV_MOVINGBED_SPEEDER 1302
#define IDS_WARN_SCAN_PV_MOVINGBED_INTEN 1303
#define IDS_WARN_SCAN_AUTO_VOICE        1304
#define IDS_WARN_SCAN_PREP_STUDY        1305
#define IDS_WARN_SCAN_PREP_DELAY_SKIP   1306
#define IDS_WARN_SCAN_DRKS_RECON_MODE   1307
#define IDS_ERR_MSG_SET_RCV_COIL        1308
#define IDS_ERR_MSG_SET_SAR_ANATOMY     1309
#define IDS_ERR_ACQ_LOCK_FILE           1310
#define IDS_WARNING_APP_NAME            1311
#define IDS_ERROR_APP_NAME              1312
#define IDS_SYSTEMNAME_NOTFOUND         1313
#define IDS_ERR_PVCOIL_FILE             1314
#define IDS_NO_IRS_NOTIFIER             1315
#define IDS_ERR_ACC_GATE_UNKNOWN        1316
#define IDS_ERR_ACC_GATE_INFO           1317
#define IDS_ERR_SCAN_ABORTED            1318
#define IDS_ERR_ILLEGAL_PROTOCOL        1319
#define IDS_ERR_SAR                     1320
#define IDS_WARN_PRESCAN_HOME_POS       1321
#define IDS_FAIL_CONNECT_ACQMAN         1322
#define IDS_ERR_CONNECT_IRS             1323
#define IDS_MSG_SET_SPEEDER             1324
#define IDS_ERR_CONNECTION_DENIED       1325
#define IDS_PROBE_STUDY_NOT_FOUND       1326
#define IDS_ERR_GP_SITES_ROOT           1327
#define IDS_ERR_GP_SITE                 1328
#define IDS_VF_HANDLE_WARNING           1329
#define IDS_ERR_PM_SHIMMING             1330
#define IDS_ERR_SAME_STUDY              1331
#define IDS_ERR_INTERLOCK_VALUES        1332
#define IDS_ERR_DBSA_GET_NEXT_SERIES    1333
#define IDS_NO_SERIES_COUNT_MISMATCH    1334
#define IDS_NO_PQM_SCRATCH_PAD          1335
#define IDS_NO_IRS                      1336
#define IDS_ERR_REFPROBE                1337
#define IDS_ERR_COPY_TO_TMP_FILE        1338
#define IDS_ERR_CANNOT_START_FLUORO     1339
#define IDS_ERR_MOVE_COUCH_PROHIBITION_ERROR 1340
#define IDS_ERR_CAN_NOT_MOVE_COUCH      1341
#define IDS_ERR_BREAST_ILLEGAL_PATIENT_DIR 1342
#define IDS_ERR_BREAST_ILLEGAL_PATIENT_POSI 1343
#define IDS_FONT_NAME                   1344
#define IDS_CS_WARNING_DIALOG_TITLE_LABEL 1345
#define IDS_CS_ERR_ILLEGAL_COIL_DB      1346
#define IDS_CS_ERR_ILLEGAL_SECTION_DB   1347
#define IDS_CS_ERR_NO_COIL_DB           1348
#define IDS_CS_ERR_NO_SECTION_DB        1349
#define IDS_CS_ERR_ILLEGAL_PQM_DATA     1350
#define IDS_CS_ERR_OFF_GROUP_COIL       1351
#define IDS_CS_WAR_DISAGREEMENT_CONNECT_DATA 1352
#define IDS_CS_WAR_CHECK_CHANNEL        1353
#define IDS_CS_WAR_CHECK_CONTINUOUSNESS 1354
#define IDS_CS_WAR_CHECK_LIST           1355
#define IDS_CS_WAR_CHECK_COMBINE_2      1356
#define IDS_CS_WAR_CHECK_COMBINE        1357
#define IDS_CS_WAR_CHECK_COMBINE_3      1358
#define IDS_CS_WAR_CHECK_PORT           1359
#define IDS_CS_WAR_CHECK_NO_POSITION    1360
#define IDS_CS_WAR_CHECK_POSITION       1361
#define IDS_CS_WAR_BAD_FIELD            1362
#define IDS_CS_WAR_NO_SELECT            1363
#define IDS_CS_WAR_UPPERCOIL_NOT_MOVE   1364
#define IDS_CS_MES_OK                   1365
#define IDS_CS_MES_SELECT_COILLIST      1366
#define IDS_CS_MES_SELECT_SECTION       1367
#define IDS_CS_MES_UPPER_1              1368
#define IDS_CS_MES_UPPER_2              1369
#define IDS_CS_MES_COMBINE              1370
#define IDS_CS_MES_BAD_FIELD            1371
#define IDS_CS_MES_CHANNEL_OVER         1372
#define IDS_CS_MES_CONTINUOUSNESS       1373
#define IDS_ERR_CONNECT_PROCON          1374
#define IDS_ERR_MAP_DRIVE               1375
#define IDS_STUDY_OPEN                  1376
#define IDS_MSG_SET_PROBE_PLAN          1377
#define IDS_PQM_SAR_RF_PROTECT          1378
#define IDS_PQM_SAR_OK_BUT_RF           1379
#define IDS_PQM_SAR_LIMIT_OVER          1380
#define IDS_PQM_SAR_COIL_PROTECT        1381
#define IDS_DUMMY_COIL_MENU             1382
#define IDS_MSG_DBDT_CALC_ERROR         1383
#define IDS_MSG_DBDT_1ST_CONTROLLED     1384
#define IDS_ERR_SET_OFFSET              1385
#define IDS_MSG_DBDT_2ND_CONTROLLED     1386
#define IDS_MSG_NO_VAP_SPACE            1387
#define IDS_MSG_DBDT_LICENSE_ERR        1388
#define IDS_MSG_MATRIX_OVER             1389
#define IDS_MSG_DBDT_CONTROLLED1        1390
#define IDS_MSG_CHANNEL_OVER            1391
#define IDS_MSG_DBDT_CONTROLLED1_PLAN_ERR 1392
#define IDS_MSG_VAP_RATIO_OVER          1393
#define IDS_MSG_DBDT_CONTROLLED1_FOV_ERR 1394
#define IDS_MSG_NO_HOST_SPACE           1395
#define IDS_MSG_DBDT_CONTROLLED2_RO_ERR 1396
#define IDS_MSG_NO_ENGINE_SPACE         1398
#define IDS_MSG_IEC_SAR_LICENSE_ERR     1399
#define IDS_MSG_OVER_2GB                1400
#define IDS_MSG_IEC_SAR_1ST_CONTROLLED  1401
#define IDS_MSG_VAP_STUDY               1402
#define IDS_MSG_IEC_SAR_2ND_CONTROLLED  1403
#define IDS_ERR_AUTO_PLAN               1404
#define IDS_ERR_ACQMAN_ECG_ELECTRODE    1405
#define IDS_ERR_ACQMAN_ECG_ELECTRODE_DONE 1406
#define IDS_MAX_CONTRASTAGENTS          1407
#define IDS_MAX_SCANANATOMY             1408
#define IDS_INVALID_CONTASTAGENT        1409
#define IDS_MOVE_COUCH_CONFIRM_OUT_RANGE 1410
#define IDS_MOVE_COUCH_CONFIRM_JUST_LIMIT 1411
#define IDS_MOVE_COUCH_CONFIRM_NO_PARENT 1412
#define IDS_MOVE_COUCH_CONFIRM_MINIMUM  1413
#define IDS_MOVE_COUCH_CONFIRM          1414
#define IDS_MOVE_COUCH_CONFIRM_PLAN     1415
#define IDS_MOVE_COUCH_CONFIRM_ROUND_LIMIT 1416
#define IDS_MOVE_COUCH_CONFIRM_COUCH_ERROR 1417
#define IDS_MAX_SARANATOMY              1418
#define IDS_WARN_SCAN_INTENSITY_COIL    1419
#define IDS_WARN_SCAN_INTENSITY_COUCH   1420
#define IDS_WARN_SCAN_INTENSITY_MAP     1421
#define IDS_WARN_SCAN_INTENSITY_AREA    1422
#define IDS_INFORM_COMMENT_DONE         1423
#define MSG_SET_SPEEDER_ERR             1424
#define ERR_ILLEGAL_SPEEDER_COIL        1425
#define ERR_PROTOCOL                    1426
#define ERR_CAN_NOT_SPEEDER_MAP         1427
#define ERR_OUT_RANGE_SPEEDER           1428
#define ERR_SPEEDER_DEGENERACY          1429
#define ERR_STUDY                       1430
#define ERR_SPEEDER_MAX_RATIO           1431
#define MSG_SET_SPEEDER_TIMEOUT         1432
#define ERR_COUCH                       1433
#define IDS_PQM_WARN_PRESCAN_PROJECTION 1434
#define IDC_BUTTON1                     1435
#define IDC_BUTTON_ANATOMY              1435
#define ID_AMB_PREP                     1435
#define IDS_ERR_DIFFERENT_PORT          1436
#define IDC_SEQINFO_EDIT                1437
#define IDC_BUTTON_GANTRY               1438
#define IDC_BUTTON_SB1                  1439
#define IDC_BUTTON_SB2                  1440
#define IDC_BUTTON_SB3                  1441
#define IDC_BUTTON_SB4                  1442
#define IDD_SCANOFFSET_GANTRY_IMAGE     1443
#define IDC_CHK_BASICSCAN               1447
#define IDC_CHK_SLAB                    1448
#define IDC_NUMBER_1                    1448
#define IDC_CHK_TR                      1449
#define IDC_CHK_SLICETHK                1450
#define IDC_CHK_SLICEGAP                1451
#define IDC_CHK_FOV                     1452
#define IDC_CHK_MATRIX                  1453
#define IDC_CHK_FLIPANGLE               1454
#define IDC_CHK_NOWRAP                  1455
#define IDC_CHK_PRESAT                  1456
#define IDC_FLOPANGLE                   1457
#define IDC_CHK_LOCIMGINFO              1458
#define IDC_BTN_SAVE                    1459
#define IDC_BTN_CLOSE                   1460
#define IDC_DEBUGINFO                   1461
#define IDC_LISTARR                     1462
#define IDC_PORTINFO                    1463
#define IDC_LISTINFO                    1464
#define IDC_ACQMON                      1465
#define IDC_PROLIMMON                   1466
#define IDC_LISTCNT                     1467
#define IDC_BTNSIZE                     1468
#define IDC_IRSMON                      1469
#define IDC_STUDYDATA                   1470
#define IDC_LISTMON                     1471
#define IDC_CLEAR                       1472
#define IDC_MONOFF                      1473
#define IDC_PRTDATA                     1474
#define IDC_COUCHINFO                   1475
#define IDC_SHIM                        1476
#define IDC_SARMON                      1477
#define IDC_ACQINFO                     1478
#define IDC_GLBDATA                     1479
#define IDC_SAR                         1480
#define IDC_STATIC_LISTINFO             1483
#define IDC_STATIC_PROTOCOLDATA         1484
#define IDC_CHK_PRESCANCOIL             1485
#define IDS_CDS_MSG_AFTER_CDS           1486
#define IDS_CDS_ERR_ILLEGAL_COIL_ID     1487
#define IDS_CDS_ERR_COIL_CDS_ABORT      1488
#define IDS_CDS_MSG_COIL_CDS_NONE       1489
#define IDS_CDS_MSG_COIL_CDS_COIL       1490
#define IDS_CDS_ERR_COIL_CDS_CONTINUE   1491
#define IDS_CDS_MES_AFTER_CDS           1492
#define IDS_CS_MES_NO_POSITION          1493
#define IDS_CS_MES_SN_DOWN              1494
#define IDS_CDS_MSG_AFTER_CDS_TIMEOUT   1495
#define IDS_TOO_LONG_DISTANCE_FROM_CENTER 1497
#define IDC_PORT_NAME_1                 1498
#define IDC_PORT_NAME_2                 1499
#define IDC_PORT_NAME_3                 1500
#define IDC_PORT_NAME_4                 1501
#define IDC_PORT_NAME_5                 1502
#define IDC_PORT_NAME_6                 1503
#define IDC_PORT_NAME_7                 1504
#define IDC_PORT_NAME_8                 1505
#define IDC_PORT_NAME_9                 1506
#define IDC_PORT_NAME_10                1507
#define IDC_PORT_NAME_11                1508
#define IDC_PORT_NAME_12                1509
#define IDC_PORT_NAME_13                1510
#define IDC_LIST_SEQ_STATIC             1511
#define IDC_ENTER_PWD_STATIC            1512
#define IDC_LIST_CONT_STATIC            1513
#define IDC_LIST_OPT_STATIC             1514
#define IDC_PWD_EDIT                    1515
#define IDC_ERR_MSG_STATIC              1516
#define IDC_MOVE_COUCH_STATIC           1517
#define IDC_MOVE_COUCH_RANGE_STATIC     1518
#define IDC_IMAGE_OFFSET_STATIC         1519
#define IDC_INJECT_TIMER_BUTTON         1520
#define IDC_EDIT_DELAY                  1521
#define IDC_STATIC_LABLE_DELAY          1522
#define IDCANCEL_DELAY                  1523
#define IDOK_DELAY                      1524
#define IDC_EDIT_DELAY_MIN              1525
#define IDC_EDIT_DELAY_SEC              1526
#define IDC_STATIC_DELAY_COLON          1527
#define IDC_STATIC_LABLE_DELAY_UNIT     1528
#define IDC_HOTKEY1                     1529
#define IDC_BUTTON_COIL_CHANNEL_MODE    1530
#define IDC_STATIC_CHANNEL_MODE         1531
#define IDC_HIGH_GAIN                   1532
#define IDC_TWAVE_SUPPRESSION           1533
#define IDC_CARDIAC                     1534
#define IDC_MRIB                        1535
#define IDC_MRIA                        1536
#define IDC_COMMAND_STATIC              1538
#define IDC_MODE_STATIC                 1539
#define IDC_FILTER_STATIC               1541
#define ID_WIRELESS_OK                  1542
#define IDC_BUTTON_SPINE_1              1543
#define IDC_BUTTON_SPINE_2              1544
#define IDC_BUTTON_SPINE_3              1545
#define IDC_BUTTON_SPINE_4              1546
#define IDC_BUTTON_SPINE_5              1547
#define IDC_BUTTON_SPINE_6              1548
#define IDC_BUTTON_SPINE_7              1549
#define IDC_BUTTON_SPINE_8              1550
#define IDC_BUTTON_SPINE_9              1551
#define IDC_BUTTON_SPINE_10             1552
#define IDC_BUTTON_SPINE_11             1553
#define IDC_BUTTON_SPINE_12             1554
#define IDC_BUTTON_SPINE_13             1555
#define IDC_BUTTON_SPINE_14             1556
#define IDC_BUTTON_SPINE_15             1557
#define IDC_BUTTON_SPINE_16             1558
#define IDC_BUTTON_SPINE_17             1559
#define IDC_BUTTON_SPINE_18             1560
#define IDC_BUTTON_SPINE_19             1561
#define IDC_BUTTON_SPINE_20             1562
#define IDC_BUTTON_SPINE_21             1563
#define IDC_BUTTON_SPINE_22             1564
#define IDC_BUTTON_SPINE_23             1565
#define IDC_BUTTON_SPINE_24             1566
#define IDC_BUTTON_SPINE_25             1567
#define IDC_BUTTON_SPINE_26             1568
#define IDC_BUTTON_SPINE_27             1569
#define IDC_BUTTON_SPINE_28             1570
#define IDC_BUTTON_SPINE_29             1571
#define IDC_BUTTON_SPINE_30             1572
#define IDC_BUTTON_SPINE_31             1573
#define IDC_BUTTON_SPINE_32             1574
#define IDC_BUTTON_SPINE_33             1575
#define IDC_BUTTON_SPINE_34             1576
#define IDC_BUTTON_SPINE_35             1577
#define IDC_BUTTON_SPINE_36             1578
#define IDC_BUTTON_SPINE_37             1579
#define IDS_MSG_MATRIX_OVER_WARNING     1580
#define IDC_AMB_STATIC_STATION          1581
#define IDC_AMB_STATIC_MASTER           1582
#define IDC_AMB_MASTER_DIRECTION        1583
#define IDC_AMB_RADIO_SUB1              1584
#define IDC_AMB_SUB1_DIRECTION          1585
#define IDC_AMB_RADIO_SUB2              1586
#define IDC_AMB_SUB2_DIRECTION          1587
#define IDC_AMB_RADIO_SUB3              1588
#define IDC_AMB_SUB3_DIRECTION          1589
#define IDC_AMB_FRAME1                  1590
#define IDC_AMB_FRAME2                  1591
#define IDC_AMB_CHECK_SHIM              1592
#define IDC_AMB_CHECK_MAP               1593
#define IDC_AMB_COMBO_MAPAUTOVOICE      1594
#define IDC_AMB_STATIC_MAPAUTOVOICE     1595
#define ID_AMB_START                    1596
#define ID_AMB_CANCEL                   1597
#define ID_AMB_ABORT                    1598
#define IDC_STATION_LABEL1              1599
#define IDC_STATION_LABEL2              1600
#define IDC_STATION_LABEL3              1601
#define IDC_STATION_LABEL4              1602
#define IDC_STATION1_SEG1               1603
#define IDC_STATION1_SEG2               1604
#define IDC_STATION1_SEG3               1605
#define IDC_STATION1_SEG4               1606
#define IDC_STATION2_SEG1               1607
#define IDC_STATION2_SEG2               1608
#define IDC_STATION2_SEG3               1609
#define IDC_STATION2_SEG4               1610
#define IDC_STATION3_SEG1               1611
#define IDC_STATION4_SEG1               1612
#define IDC_STATION5_SEG1               1613
#define IDC_STATION6_SEG1               1614
#define IDC_STATION3_SEG2               1615
#define IDC_STATION3_SEG3               1616
#define IDC_STATION3_SEG4               1617
#define IDC_STATION4_SEG2               1618
#define IDC_STATION4_SEG3               1619
#define IDC_STATION4_SEG4               1620
#define IDC_STATION5_SEG2               1621
#define IDC_STATION5_SEG3               1622
#define IDC_STATION5_SEG4               1623
#define IDC_STATION6_SEG2               1624
#define IDC_STATION6_SEG3               1625
#define IDC_STATION6_SEG4               1626
#define IDC_STATION_LABEL5              1627
#define IDC_STATION_LABEL6              1628
#define IDC_MASTER_SETTING_LABEL        1629
#define IDC_STATION_FRAME               1630
#define ID_START_VOICEMENU_ITEM         3000
#define ID_START_VOICEMENU_ITEM_MAX     3099
#define ID_START_LANGUAGEMENU_ITEM      4000
#define ID_START_LANGUAGEMENU_ITEM_MAX  4099
#define IDR_AMB_ITERATION_MENU          28686
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_MENUITEM_PAS_GETMEM          32771
#define ID_MENUITEM_PAS_STORE           32772
#define ID_MENUITEM_PAS_STORE_EZPAS     32773
#define ID_MENUITEM_SET_SCAN_OFFSET     32774
#define ID_MENUITEM_INFO_SEQ            32775
#define ID_MENUITEM_INFO_COIL           32776
#define ID_MENUITEM_INFO_GATE           32777
#define ID_MENUITEM_AUTO_PLAN           32778
#define ID_MENUITEM_PLAN_SCAN           32779
#define ID_MENUITEM_SKIP_RGN            32780
#define ID_MENUITEM_ALL_COV_RGN         32781
#define ID_MENUITEM_SPEEDERMAP_AUTOVOICE 32782
#define ID_MENUITEM_MULTI_COV_CAUTION   32783
#define ID_MENUITEM_BATCH_COIL_AND_SAR_RGN 32784
#define ID_MENUITEM_GATE_MODE_ECG       32785
#define ID_MENUITEM_GATE_MODE_PERIPHERAL 32786
#define ID_MENUITEM_GATE_MODE_RESPIRATORY 32787
#define ID_MENUITEM_PREP_WB_COIL        32788
#define ID_MENUITEM_SHIMMING_WB_COIL    32789
#define ID_MENUITEM_APC_RETRY           32790
#define ID_MENUITEM_APC_PAUSE           32791
#define ID_MENUITEM_CENTER_FREQ_CTRL    32792
#define ID_MENUITEM_ELECTRODE_I         32793
#define ID_MENUITEM_ELECTRODE_II        32794
#define ID_MENUITEM_ELECTRODE_III       32795
#define ID_MENUITEM_ELECTRODE_AVR       32796
#define ID_MENUITEM_ELECTRODE_AVL       32797
#define ID_MENUITEM_ELECTRODE_AVF       32798
#define ID_ORIENTATION1_1               32799
#define ID_ORIENTATION1_2               32800
#define ID_ORIENTATION2_1               32801
#define ID_ORIENTATION2_2               32802
#define ID_ORIENTATION2_3               32803
#define ID_ORIENTATION2_4               32804
#define ID_ORIENTATION3_1               32805
#define ID_ORIENTATION3_2               32806
#define ID_MENUITEM_N_N                 32807
#define ID_MENUITEM_N_B1                32808
#define ID_MENUITEM_N_B2                32809
#define ID_MENUITEM_N_B3                32810
#define ID_MENUITEM_N_M1                32811
#define ID_MENUITEM_B1_N                32812
#define ID_MENUITEM_B1_B1               32813
#define ID_MENUITEM_B1_B2               32814
#define ID_MENUITEM_B1_B3               32815
#define ID_MENUITEM_B1_M1               32816
#define ID_MENUITEM_B2_N                32817
#define ID_MENUITEM_B2_B1               32818
#define ID_MENUITEM_B2_B2               32819
#define ID_MENUITEM_B2_B3               32820
#define ID_MENUITEM_B2_M1               32821
#define ID_MENUITEM_B3_N                32822
#define ID_MENUITEM_B3_B1               32823
#define ID_MENUITEM_B3_B2               32824
#define ID_MENUITEM_B3_B3               32825
#define ID_MENUITEM_B3_M1               32826
#define ID_MENUITEM_M1_N                32827
#define ID_MENUITEM_M1_B1               32828
#define ID_MENUITEM_M1_B2               32829
#define ID_MENUITEM_M1_B3               32830
#define ID_MENUITEM_M1_M1               32831
#define ID_OPEN_PROBEPLAN               32832
#define ID_OPEN_PROBEEDIT               32833
#define ID_MENUITEM_ADJUST_CENTER_FREQUENCY 32834
#define ID_MENUITEM_DUMMY               32835
#define ID_PROTOCOL_AUTO_SCAN           32836
#define ID_SET_ALL                      32837
#define ID_COMMENT                      32838
#define ID_CONTRAST_AGENT_GADOLINIUM    32839
#define ID_AUTO_SCAN                    32840
#define ID_MENUITEM_MANUAL_PRESCAN      32841
#define ID_MENUITEM_VOICE               32842
#define ID_MOVING_TO_LOCATOR_IMAGE      32843
#define ID_PROTOCOLMENU_PLANDUPLICATE   32844
#define ID_PROTOCOL_REFERROI            32845
#define ID_PROTOCOLMENU_BREATHHOLD      32846
#define ID_PROTOCOLMENU_AUTOTRANSFER    32847
#define ID_PROTOCOLMENU_MOVECOUCH       32848
#define ID_PROTOCOLMENU_SFT             32849
#define ID_PROTOCOLMENU_VFC             32850
#define ID_PROTOCOLMENU_SFT_ADJUSTF1F2  32851
#define ID_MENUITEM_PLNDUP_CONFIG       32852
#define ID_PROTOCOLMENU_NO_MOVE         32853
#define ID_MOVECOUCHMENU_CENTER_OF_THE_PLAN 32854
#define ID_UTILITY_DEBUGINFO            32856
#define ID_UTILITY_MENU_AS_COMPASS_SETTING 32857
#define ID_ENABLE_CDS_DEBUG             32858
#define ID_ENABLE_AS_COMPASS            32859
#define ID_MRS_EDDY_SEQUENCE            32860
#define ID_CALC_MRS_EDDY                32861
#define ID_CALC_MRS_EDDY_DIF            32862
#define ID_ECC_MRS_SHORT                32863
#define ID_MOVECOUCHMENU_POSITION_OF_REFERENCE_IMAGE 32864
#define ID_PROTOCOLMENU_APPEND          32866
#define ID_PROTOCOLMENU_DELETE          32867
#define ID_COPY_TO_COMMENT              32868
#define ID_UTILITY_VOICE                32869
#define ID_CALA_CARDIAC_LOCATOR         32870
#define ID_PLAN_RESET                   32871
#define ID_PROTOCOLMENU_EDITDELAY       32872
#define ID_MENU_NORMAL                  32873
#define ID_MENU_MAX                     32874
#define ID_WIRELESS_GATING_MENU         32875
#define ID_CARDIAC_LOCATOR              32876
#define ID_NEURO_LOCATOR                32877
#define ID_LOCATOR_CONCIERGE            32878
#define ID_ITERATION1                   32879
#define ID_MENU_TIPREP                  32879
#define ID_ITERATION2                   32880
#define ID_ITERATION3                   32881
#define ID_ITERATION4                   32882
#define ID_PROTOCOLMENU_AMB             32883
#define ID_G_MENU_DYNAMIC               50000
#define ID_G_MENU_DYNAMIC_MAX           50099
#define ID_L_MENU_DYNAMIC               50100
#define ID_L_MENU_DYNAMIC_MAX           50199
#define ID_A_MENU_DYNAMIC               50200
#define ID_A_MENU_DYNAMIC_MAX           50299
#define ID_PORT_MENU_DYNAMIC            50300
#define ID_PORT_MENU_DYNAMIC_MAX        50309
#define ID_POS_MENU_DYNAMIC             50310
#define ID_POS_MENU_DYNAMIC_MAX         50324
#define ID_CONTRAST_POPUP_MENU          50325
#define ID_CONTRAST_POPUP_MENU_MAX      50349
#define ID_MENU_SCAN_ANATOMY            50350
#define ID_MENU_SCAN_ANATOMY_MAX        50399
#define ID_POPUP_DYNCMD01               50400
#define ID_POPUP_DYNCMD01_MAX           50499
#define ID_LATERALITY_MENU_MIN          50500
#define ID_LATERALITY_MENU_MAX          50549
#define ID_SFT_MENU_MIN                 50550
#define ID_SFT_MENU_MAX                 50599
#define ID_TOOL_MENU_MIN                50600
#define ID_TOOL_MENU_MAX                50649
#define ID_PLANDUPLICATE_MIN            50650
#define ID_PLANDUPLICATE_MAX            50699
#define IDS_NO_WAIT_PROTOCOLS           61204
#define ERR_SYSTEM_SAR_DISPLAY          61205
#define OP_ERROR_MRS_PARENT             61206
#define OP_ERROR_HR                     61207
#define OP_ERROR_MRS_ROI                61208
#define IDS_ERR_COUCH                   61209
#define IDS_ERR_ACC_TXCOIL              61210
#define IDS_ERR_TXCOIL                  61211
#define IDS_ERR_ACC_RXCOIL              61212
#define IDS_ERR_RXCOIL                  61213
#define IDS_ERR_ACC_GATEMETHOD          61214
#define IDS_ERR_GATEMETHOD              61215
#define IDS_ERR_ACC_SEQGEN              61216
#define IDS_ERR_SEQGEN                  61217
#define IDS_ERR_ACC_SAR                 61218
#define IDS_ERR_SAR_PRESCAN             61219
#define IDS_ERR_ACC_SAR_COIL            61220
#define IDS_ERR_SAR_COIL                61221
#define IDS_ERR_FRM_ACC_PRESCAN         61222
#define IDS_ERR_PRESCAN                 61223
#define IDS_ERR_ACC_NAK                 61224
#define IDS_ERR_NAK                     61225
#define IDS_ERR_ACC_COUCH               61226
#define IDS_ERR_COIL_RESELECT           61227
#define IDS_ERR_COIL_DISCONNECT         61228
#define IDS_ERR_COIL_DATA               61229
#define IDS_ERR_CAN_NOT_CONNECT_PROCON  61230
#define IDS_ERR_OFF_GROUP_COIL          61231
#define IDS_ERR_PQM_NOT_CLOSED          61232
#define IDS_SCAN_GOING_ON               61233
#define IDS_DBDT_DIALOG_STRING          61234
#define IDS_ERR_BREAST_ILLEGAL_PATIENT  61235
#define IDS_OP_ERROR_HR                 61236
#define IDS_OP_ERROR_MRS                61237
#define IDS_OP_ERROR_MRS_ROI            61238
#define IDS_OP_ERROR_MRS_SHIM           61239
#define IDS_OP_ERROR_MRS_PARENT         61240
#define IDS_ERR_DB_NOT_SYNC             61241
#define IDC_MRSDIALOG_WATER_SATURATION_REF_CHECK 61242
#define IDS_WARN_JET_CHANNEL            61243
#define IDS_JETCHANNEL_V_NOT_FOUND      61244
#define ERR_ILLEGAL_COIL_ID             61245
#define IDS_JETCHANNEL_V_ILLEGAL_VALUE_FOUND 61246
#define IDS_CS_ERR_ILLEGAL_COIL_ID      61247
#define IDS_ERR_MSG_STUDY_WRITE_ERROR   61248
#define ERR_OVER_COILWEIGHT             61249
#define IDS_VISUAL_PREP_POSITIONING_NOT_DONE 61250
#define IDS_PQM_WARN_PRESCAN_PVC_COUCH_POSI 61251
#define IDS_WARN_SCAN_DEGENERACY_MAP    61252
#define IDS_PQM_LIST_STUDY_PROTOCOL_MISMATCH 61253
#define IDS_SCAN_NOT_PERFORM            61254
#define IDS_PQM_WARN_PRESCAN_PUMP_AND_FREEZER 61255
#define IDS_PQM_WARN_PRESCAN_PUMP       61256
#define IDS_PQM_WARN_PRESCAN_FREEZER    61257
#define IDS_FAIL_READ_SMCF_FILE         61258
#define IDS_OP_ERROR_RESULT             61259
#define IDS_OP_ERROR_MS                 61260
#define IDS_OP_SHIM_FATAL_ERROR         61261
#define IDS_OP_MRS_MS_LIMIT_ERROR       61262
#define IDS_PQM_INCORRECT_PROTOCOL_SCANREQUEST 61263
#define IDS_CS_ERR_NO_PATH_DB           61264
#define IDS_CS_ERR_ILLEGAL_PATH_DB      61265
#define IDS_MSG_IMGSRV_MEMORY           61266
#define IDS_ERR_PQM_REMOTE_CONSOLE      61267
#define IDS_ERR_PAUSE_PQM_REMOTE_CONSOLE 61268
#define IDS_ERR_ABORT_PQM_REMOTE_CONSOLE 61269
#define IDS_MSG_NO_LOCALDB_SPACE        61270
#define IDS_PQM_NO_MOVE                 61271
#define IDS_PQM_CENTER_OF_THE_PLAN      61272
#define IDS_PQM_POSITION_OF_REF_IMAGE   61273
#define IDS_PQM_PRESCANCOIL             61274
#define IDS_MSG_SHIMMING_TIMEOUT        61275
#define IDS_ERR_MOVING_COUCH            61276
#define IDS_ERR_ACC_GCOILTEMP           61277
#define IDS_ERR_GAMPTEMP                61278
#define IDS_ERR_GCOILTEMP               61279
#define IDS_CONFIG_ERROR                61280
#define IDS_ERR_PQM_MRS_PRESCAN_START   61281
#define IDS_ERR_PQM_ABORT_MRS_PRESCAN   61282
#define IDS_ERR_RESUME_PQM_REMOTE_CONSOLE 61283
#define IDS_INVALID_PASSWORD            61284
#define IDS_ERR_OLPTEMP_MEASUREMENT     61285
#define IDS_ERR_OLPTEMP_MEASUREMENT_DONE 61286
#define IDC_MRSDIALOG_LOCAL_SHIMMING_CHECK 61287
#define IDC_MRSDIALOG_SPECTRUM_GRAPH_CHECK 61288
#define ERR_B1_UNIFORMITY               61289
#define IDS_AUTOINSERT_CONFIG_FILE_MISSING 61290
#define ID_INVALID_CALA_PROTOCOL_PARAM  61291
#define IDS_INVALID_CALCULATED_STATUS   61292
#define IDS_CARDIAC_LOCATOR_TIMEOUT     61293
#define IDS_ERR_SCAN_EDIT_NOT_DONE      61294
#define ERR_TX_INTENSITY_NOTFOUND       61295
#define ERR_INTENSITY_NOTFOUND          61296
#define ID_PLAN_MASTER_BIAS_MIN         61297
#define ID_PLAN_MASTER_BIAS_MAX         61421
#define IDS_DELAY_TIME_INVALID          61422
#define IDS_DELAY_TIME_CANNOT_SET       61423
#define IDS_MSG_OVER_MRS_DATA_WARNING   61424
#define ID_UTILITY_SARMANAGER           61425

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        418
#define _APS_NEXT_COMMAND_VALUE         32880
#define _APS_NEXT_CONTROL_VALUE         1581
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
