/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User.Interface.SupplierAdminRole;

import Business.MedicalDevice.MedicalDevice;
import Business.MedicalDevice.MedicalDevice.Catagory;
import Business.Organization.SupplierAdminOrganization;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asha
 */
public class ManageMedicalDeviceCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMedicalDeviceCatalog
     */
    private JPanel userProcessContainer;
    private SupplierAdminOrganization supplierAdminOrganization;

    public ManageMedicalDeviceCatalogJPanel(JPanel userProcessContainer, SupplierAdminOrganization supplierAdminOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierAdminOrganization = supplierAdminOrganization;
         Color c = new Color(0, 85, 119);
        this.setBackground(c);
        populateTable();
        populateDeviceCatagoryComboBox();
        
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) devicejTable.getModel();
        model.setRowCount(0);

        for (MedicalDevice md : supplierAdminOrganization.getMedicalDeviceCatalog().getMedicalDeviceList()) {
            Object[] row = new Object[3];
            row[0] = md;
            row[1] = md.getDeviceId();
            row[2] = md.getPrice();

            model.addRow(row);
        }
    }

    public void populateDeviceCatagoryComboBox() {
      //  catagoryjComboBox.removeAllItems();
        //catagoryjComboBox.addItem(this);
        
//            catagoryjComboBox.addItem(MedicalDevice.Catagory.Class_I.getValue());
//            catagoryjComboBox.addItem(MedicalDevice.Catagory.Class_II.getValue());
//            catagoryjComboBox.addItem(MedicalDevice.Catagory.Class_III.getValue());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        devicejTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        deleteDevicejTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        addDevicejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        catagoryjComboBox = new javax.swing.JComboBox();
        deviceNamejTextField = new javax.swing.JTextField();
        modelNamejTextField = new javax.swing.JTextField();
        pricejTextField = new javax.swing.JTextField();
        serviceIntervaljComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        safetyGuidelinejTextArea = new javax.swing.JTextArea();
        manufactureDatejXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        quantityjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        searchNamejTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        deleteDevicejButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        viewPButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 85, 119));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(255, 255, 255));
        titlejLabel.setText("Supplier Admin - Manage Medical Device Catalog");

        devicejTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devicejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device Name", "Device ID", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        devicejTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(devicejTable);

        refreshButton.setBackground(new java.awt.Color(30, 30, 30));
        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Refresh");
        refreshButton.setMargin(new java.awt.Insets(2, 1, 2, 1));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        deleteDevicejTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(0, 82, 119));

        addDevicejButton.setBackground(new java.awt.Color(30, 30, 30));
        addDevicejButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addDevicejButton.setForeground(new java.awt.Color(255, 255, 255));
        addDevicejButton.setText("Add Device");
        addDevicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDevicejButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catagory");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Model Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manufacture Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Service Interval");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Safety Guideline");

        catagoryjComboBox.setBackground(new java.awt.Color(120, 120, 120));
        catagoryjComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catagoryjComboBox.setForeground(new java.awt.Color(255, 255, 255));
        catagoryjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class_I", "Class_II", "ClassIII" }));

        deviceNamejTextField.setBackground(new java.awt.Color(120, 120, 120));
        deviceNamejTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deviceNamejTextField.setForeground(new java.awt.Color(255, 255, 255));

        modelNamejTextField.setBackground(new java.awt.Color(120, 120, 120));
        modelNamejTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modelNamejTextField.setForeground(new java.awt.Color(255, 255, 255));

        pricejTextField.setBackground(new java.awt.Color(120, 120, 120));
        pricejTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pricejTextField.setForeground(new java.awt.Color(255, 255, 255));

        serviceIntervaljComboBox.setBackground(new java.awt.Color(120, 120, 120));
        serviceIntervaljComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        serviceIntervaljComboBox.setForeground(new java.awt.Color(255, 255, 255));
        serviceIntervaljComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        safetyGuidelinejTextArea.setBackground(new java.awt.Color(120, 120, 120));
        safetyGuidelinejTextArea.setColumns(20);
        safetyGuidelinejTextArea.setForeground(new java.awt.Color(255, 255, 255));
        safetyGuidelinejTextArea.setRows(5);
        jScrollPane2.setViewportView(safetyGuidelinejTextArea);

        manufactureDatejXDatePicker.setBackground(new java.awt.Color(120, 120, 120));
        manufactureDatejXDatePicker.setForeground(new java.awt.Color(255, 255, 255));

        quantityjTextField.setBackground(new java.awt.Color(120, 120, 120));
        quantityjTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quantityjTextField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("months");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deviceNamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(pricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catagoryjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manufactureDatejXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(serviceIntervaljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(addDevicejButton)))
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {catagoryjComboBox, deviceNamejTextField, manufactureDatejXDatePicker, modelNamejTextField, pricejTextField, quantityjTextField, serviceIntervaljComboBox});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(catagoryjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(modelNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deviceNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(quantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(serviceIntervaljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(manufactureDatejXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addDevicejButton)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {catagoryjComboBox, deviceNamejTextField, manufactureDatejXDatePicker, modelNamejTextField, pricejTextField, quantityjTextField, serviceIntervaljComboBox});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        deleteDevicejTabbedPane.addTab("Add Device", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 82, 119));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search by Name");

        searchNamejTextField.setBackground(new java.awt.Color(120, 120, 120));
        searchNamejTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchNamejTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNamejTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(searchNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(searchNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        deleteDevicejTabbedPane.addTab("Search Device", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 82, 119));

        deleteDevicejButton.setBackground(new java.awt.Color(30, 30, 30));
        deleteDevicejButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteDevicejButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteDevicejButton.setText("Delete Device");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select a device from the table and click 'Delete Device' button");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(deleteDevicejButton))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9)
                .addGap(44, 44, 44)
                .addComponent(deleteDevicejButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        deleteDevicejTabbedPane.addTab("Delete Device", jPanel2);

        viewPButton.setBackground(new java.awt.Color(30, 30, 30));
        viewPButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewPButton.setForeground(new java.awt.Color(255, 255, 255));
        viewPButton.setText("View Product Details");
        viewPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPButtonActionPerformed(evt);
            }
        });

        backButton4.setBackground(new java.awt.Color(30, 30, 30));
        backButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton4.setForeground(new java.awt.Color(255, 255, 255));
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titlejLabel)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(deleteDevicejTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPButton)
                    .addComponent(refreshButton)
                    .addComponent(backButton4))
                .addGap(18, 18, 18)
                .addComponent(deleteDevicejTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backButton4, refreshButton, viewPButton});

    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        //refreshTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void viewPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPButtonActionPerformed
        // TODO add your handling code here:
        int supplierCount = supplierAdminOrganization.getMedicalDeviceCatalog().getMedicalDeviceList().size();
        if (supplierCount < 1) {
            JOptionPane.showMessageDialog(this, "No Products avaialable to display.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int selectedRow = devicejTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a product from the list.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        MedicalDevice p = (MedicalDevice) devicejTable.getValueAt(selectedRow, 0);
        if (null == p) {
            JOptionPane.showMessageDialog(this, "Failed to retrieve selected product's information.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ViewDeviceDetailJPanel vpdjp = new ViewDeviceDetailJPanel(userProcessContainer, p);
        userProcessContainer.add("ViewDeviceDetailJPanel", vpdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton4ActionPerformed

    private void addDevicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDevicejButtonActionPerformed
        // TODO add your handling code here:
        Catagory deviceCatagory = null;

        String deviceName = deviceNamejTextField.getText();

        String modelName = modelNamejTextField.getText();

        double price = 0;
        try{
            price = Double.parseDouble(pricejTextField.getText());
         }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Please enter a valid price");
             return;
         }
        
        int quantity = 0;
        try{
             quantity = Integer.parseInt(quantityjTextField.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity");
            return;
        }
        
        int serviceInterval = 0;
       try{
           int i = serviceIntervaljComboBox.getSelectedIndex();
           quantity = Integer.parseInt((String) serviceIntervaljComboBox.getItemAt(i));
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Please enter a service interval");
             return;
        }
       
        Date manufacutureDate = manufactureDatejXDatePicker.getDate();

        //int serviceInterval = serviceIntervaljComboBox.getselect;
        String safetyGuideline = safetyGuidelinejTextArea.getText();

        boolean isValid = validateUserInput(deviceCatagory,
                deviceName,
                modelName,
                price,
                quantity,
                manufacutureDate,
                quantity,
                safetyGuideline);
        if (false == isValid) {
            return;
        }

        //add the device to the catalog
        supplierAdminOrganization.getMedicalDeviceCatalog().addDevice(deviceCatagory,
                deviceName,
                modelName,
                price,
                quantity,
                manufacutureDate,
                serviceInterval,
                safetyGuideline);
        populateTable();
    }//GEN-LAST:event_addDevicejButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //get the name
        String name = jButton1.getText();
        if(true == name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid device id");
            return;
        }
        int id = 0;
        try{
            id = Integer.parseInt(name);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter a valid device id");
            return;
        }
        MedicalDevice md = supplierAdminOrganization.getMedicalDeviceCatalog().searchProduct(id);
        ViewDeviceDetailJPanel vpdjp = new ViewDeviceDetailJPanel(userProcessContainer, md);
        userProcessContainer.add("ViewDeviceDetailJPanel", vpdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNamejTextFieldActionPerformed

    private boolean validateUserInput(Catagory deviceCatagory,
            String deviceName,
            String modelName,
            double price,
            int quantity,
            Date manufacutureDate,
            int serviceInterval,
            String safetyGuideline) {
        if(true == deviceName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid device name");
            return false;
        }
        
         if(true == modelName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid model name");
            return false;
        }
         
         if(true == deviceName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid safety guideline");
            return false;
        }       
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDevicejButton;
    private javax.swing.JButton backButton4;
    private javax.swing.JComboBox catagoryjComboBox;
    private javax.swing.JButton deleteDevicejButton;
    private javax.swing.JTabbedPane deleteDevicejTabbedPane;
    private javax.swing.JTextField deviceNamejTextField;
    private javax.swing.JTable devicejTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker manufactureDatejXDatePicker;
    private javax.swing.JTextField modelNamejTextField;
    private javax.swing.JTextField pricejTextField;
    private javax.swing.JTextField quantityjTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextArea safetyGuidelinejTextArea;
    private javax.swing.JTextField searchNamejTextField;
    private javax.swing.JComboBox serviceIntervaljComboBox;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JButton viewPButton;
    // End of variables declaration//GEN-END:variables
}
