/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package User.Interface.SystemAdminRole;

import Bsuiness.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asha
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
         Color c = new Color(0, 85, 119);
        this.setBackground(c);
        populateEnterpriseTable();
        popuateNetworkAndEnterprise();
    }

    private void populateEnterpriseTable(){
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();                
        model.setRowCount(0);
        
        if(0 >= system.getNetworkList().size()){
            //pending status
            return;
        }
        
        for (Network network : system.getNetworkList()){
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                Object[] row = new Object[3];
                row[0] = enterprise;
                row[1] = network;
                row[2] = enterprise.getEnterpriseType().getValue();                
                model.addRow(row);
            }
        }
    }
    
    private void popuateNetworkAndEnterprise(){
        networkJComboBox.removeAllItems();
        enterpriseTypeJComboBox.removeAllItems();
        
        for (Network l_network : system.getNetworkList()){
            networkJComboBox.addItem(l_network);
        }
        
        for (Enterprise.EnterpriseType l_type : Enterprise.EnterpriseType.values()){
            enterpriseTypeJComboBox.addItem(l_type);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        networkjLabel = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseNamejLabel = new javax.swing.JLabel();
        enterpriseNameJTextField = new javax.swing.JTextField();
        enterpriseTypejLabel = new javax.swing.JLabel();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        addEnterpriseJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        titlejLabel = new javax.swing.JLabel();
        addEnterprisejLabel = new javax.swing.JLabel();
        deleteEnterprisejLabel = new javax.swing.JLabel();
        deleteEnterpriseJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 85, 119));
        setForeground(new java.awt.Color(255, 255, 255));

        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        networkjLabel.setText("Network");

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriseNamejLabel.setText("Enterprise Name");

        enterpriseTypejLabel.setText("Enterprise Type");

        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addEnterpriseJButton.setText("Add Enterprise");
        addEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel.setText("System Admin - Manage Enterprise");

        addEnterprisejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addEnterprisejLabel.setText("Add Enterprise");

        deleteEnterprisejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteEnterprisejLabel.setText("Delete Enterprise");

        deleteEnterpriseJButton.setText("Delete Enterprise");
        deleteEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnterpriseJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(titlejLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addEnterpriseJButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enterpriseNamejLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(networkjLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(enterpriseTypejLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteEnterpriseJButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addEnterprisejLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteEnterprisejLabel))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titlejLabel)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEnterprisejLabel)
                    .addComponent(deleteEnterprisejLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkjLabel)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEnterpriseJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseTypejLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterpriseNamejLabel)
                    .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEnterpriseJButton)
                .addGap(23, 23, 23)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseJButtonActionPerformed

        //get the selected network
        Network l_network = (Network) networkJComboBox.getSelectedItem();
        if(null == l_network){
            //pending error
            return;
        }
        
        //get the enterprise type
        Enterprise.EnterpriseType l_type = (Enterprise.EnterpriseType)enterpriseTypeJComboBox.getSelectedItem();       
        if ((null == l_network) || (null == l_type)){
            //pending error
            return;
        }
        
        //get the enterprise name
        String l_enterpriseName = enterpriseNameJTextField.getText();
        if((null == l_enterpriseName) || (true == l_enterpriseName.isEmpty())){
            JOptionPane.showMessageDialog(this, "Please enter a valid enterprise name!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //create and add new enterprise
        Enterprise l_enterprise = l_network.getEnterpriseDirectory().createAndAddEnterprise(l_enterpriseName, l_type);
        if(null == l_enterprise){
            //pending status            
        }
        populateEnterpriseTable();        
    }//GEN-LAST:event_addEnterpriseJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void deleteEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        //get the selected enterprise
        int selectedRow = enterpriseJTable.getSelectedRow();
        if (0 > selectedRow) {
            JOptionPane.showMessageDialog(this, "Please select an enterprise from the list.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Enterprise  l_enterprise = (Enterprise) enterpriseJTable.getValueAt(selectedRow, 0);
        if(null == l_enterprise){
            //pending status
            return;
        }
        
        //get the selected enterprise's network
        //pending
        
        //delete the enterprise from the network
        //pending
        
        populateEnterpriseTable();        
    }//GEN-LAST:event_deleteEnterpriseJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseJButton;
    private javax.swing.JLabel addEnterprisejLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteEnterpriseJButton;
    private javax.swing.JLabel deleteEnterprisejLabel;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JTextField enterpriseNameJTextField;
    private javax.swing.JLabel enterpriseNamejLabel;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel enterpriseTypejLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JLabel networkjLabel;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
