/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User.Interface.SystemAdminRole;

import Bsuiness.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Asha
 */
public class ManageInventoryEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageInventoryEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
 Color c = new Color(0, 85, 119);
        this.setBackground(c);
        this.userProcessContainer = userProcessContainer;
        this.system = system;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel1 = new javax.swing.JLabel();
        manageOrganizationjButton = new javax.swing.JButton();
        manageEmployeesjButton = new javax.swing.JButton();
        manageUserAccountsjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 85, 119));
        setForeground(new java.awt.Color(255, 255, 255));

        titlejLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlejLabel1.setText("System Admin - Manage Inventory Enterprise");

        manageOrganizationjButton.setText("Manage Organization");
        manageOrganizationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationjButtonActionPerformed(evt);
            }
        });

        manageEmployeesjButton.setText("Manage Employees");
        manageEmployeesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesjButtonActionPerformed(evt);
            }
        });

        manageUserAccountsjButton.setText("Manage User Accounts");
        manageUserAccountsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(titlejLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageUserAccountsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEmployeesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageOrganizationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titlejLabel1)
                .addGap(31, 31, 31)
                .addComponent(manageOrganizationjButton)
                .addGap(18, 18, 18)
                .addComponent(manageEmployeesjButton)
                .addGap(18, 18, 18)
                .addComponent(manageUserAccountsjButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationjButtonActionPerformed
        // TODO add your handling code here:
        ManageInventoryOrganizationJPanel panel = new ManageInventoryOrganizationJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageInventoryOrganizationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationjButtonActionPerformed

    private void manageEmployeesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesjButtonActionPerformed
        // TODO add your handling code here:
        ManageInventoryEmployeeJPanel panel = new ManageInventoryEmployeeJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageInventoryEmployeeJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeesjButtonActionPerformed

    private void manageUserAccountsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountsjButtonActionPerformed
        // TODO add your handling code here:
        ManageInventoryUserAccountJPanel panel = new ManageInventoryUserAccountJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageInventoryUserAccountJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageEmployeesjButton;
    private javax.swing.JButton manageOrganizationjButton;
    private javax.swing.JButton manageUserAccountsjButton;
    private javax.swing.JLabel titlejLabel1;
    // End of variables declaration//GEN-END:variables
}
