//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TiPrep.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDP_OLE_INIT_FAILED             100
#define IDD_TIPREP_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_TIPREPTYPE                  129
#define IDD_TIPREP_DIALOG               130
#define IDR_MENU1                       131
#define IDD_DIALOG_COPYROI              133
#define IDD_DIALOG_RECON                134
#define IDD_DIALOG_SETROI               137
#define IDD_DIALOG_ERROR                138
#define IDB_BITMAP1                     139
#define IDD_POLARITY_CORRECTION         140
#define IDD_DIALOG_ADD_OFFSET           141
#define IDD_DIALOG_MANUAL_INITIAL_GUESS 142
#define IDD_DIALOG_MANUAL_PHASE_CORR    143
#define IDD_DIALOG_ABOUT                144
#define IDI_TIPREP_ICON                 145
#define IDI_TIPREP_ICON2                146
#define IDD_PROGRESS_DIALOG             147
#define IDD_DIALOG_APPLY_TI             148
#define IDC_EDIT_GRAPH                  1003
#define IDC_EDIT_ROIPARAMS1_CENY        1004
#define IDC_EDIT_PROT_FOR_RECON         1005
#define IDC_BUTTON_ROICOPY              1006
#define IDC_STATIC_FRAME_DISPLAY_OPTION 1007
#define IDC_STATIC_DISPLAYOPTION        1008
#define IDC_STATIC_ORGDATA              1009
#define IDC_STATIC_INVDATA              1010
#define IDC_CHECK_ORGDATA               1011
#define IDC_CHECK_INVDATA               1012
#define IDC_CHECK_FITDATA               1013
#define IDC_CHECK_EDITROI               1014
#define IDC_STATIC_FRAME_CALCULATED_DATA 1015
#define IDC_STATIC_ROI1                 1016
#define IDC_STATIC_ROI2                 1017
#define IDC_STATIC_CENTER_X             1018
#define IDC_STATIC_ROI3                 1019
#define IDC_STATIC_CENTER_Y             1020
#define IDC_STATIC_DISPLAY              1021
#define IDC_STATIC_ROI1_PARAMS          1022
#define IDC_CHECK_ROI1_DISLPAY          1023
#define IDC_EDIT_ROI1_CENX              1024
#define IDC_CHECK_ROI2_DISPLAY          1025
#define IDC_EDIT_ROI1_CENY              1026
#define IDC_CHECK_ROI3_DISPLAY          1027
#define IDC_EDIT_ROI1_RADIUS            1028
#define IDC_STATIC_REVERSEMIN           1029
#define IDC_STATIC_ROI2_PARAMS          1030
#define IDC_CHECK_ROI1_REVERSEMIN       1031
#define IDC_EDIT_ROI2_CENX              1032
#define IDC_CHECK_ROI2_REVERSEMIN       1033
#define IDC_EDIT_ROI2_RADIUS            1034
#define IDC_STATIC_INVDATA2             1035
#define IDC_STATIC_ROI3_PARAMS          1036
#define IDC_EDIT_ROI3_CENX              1037
#define IDC_EDIT_ROI3_CENY              1038
#define IDC_CHECK_ROI3_DISPLAY_NEW      1039
#define IDC_EDIT_ROI3_RADIUS            1040
#define IDC_STATIC_FITTINGERROR         1041
#define IDC_STATIC_ERROR                1042
#define IDC_EDIT_ROI1FITTINGERROR       1043
#define IDC_EDIT_ROI2FITTINGERROR       1044
#define IDC_BUTTON_SAVE                 1045
#define IDC_EDIT_ROI3FITTINGERROR       1046
#define IDC_STATIC_MEAN                 1047
#define IDC_STATIC_INVERSIONTIME        1048
#define IDC_STATIC_RECOVERYTIME         1049
#define IDC_EDIT_ROI1TI                 1050
#define IDC_EDIT_ROI2TI                 1051
#define IDC_EDIT_ROI3TI                 1052
#define IDC_EDIT_MEANTI                 1053
#define IDC_EDIT_ROI1T1                 1054
#define IDC_EDIT_ROI2T1                 1055
#define IDC_EDIT_ROI3T1                 1056
#define IDC_EDIT_MEANT1                 1057
#define IDC_STATIC_ADDROIAVERAGE        1060
#define IDC_STATIC_OFFSET               1064
#define IDC_EDIT_OFFSET                 1065
#define IDC_STATIC_FRAME_PHASE_CALCULATE 1067
#define IDC_STATIC_MG                   1068
#define IDC_EDIT_MG                     1069
#define IDC_BUTTON_SELECTMG             1070
#define IDC_STATIC_RE                   1071
#define IDC_EDIT_RE                     1072
#define IDC_BUTTON_SELECTRE             1073
#define IDC_STATIC_IM                   1074
#define IDC_EDIT_IM                     1075
#define IDC_BUTTON_SELECTIM             1076
#define IDC_BUTTON_CORRECTPHASE         1077
#define IDC_EDIT_WIDTH_ROI5             1078
#define IDC_EDIT_ROIPARAMS2_CENY        1079
#define IDC_EDIT_ROI2_CENY              1080
#define IDC_STATIC_FRAME_EQUETN_WINDOW  1081
#define IDC_STATIC_REPETITIONTIME       1082
#define IDC_EDIT_REPETITIONTIME         1083
#define IDC_BUTTON_EXIT                 1084
#define IDC_BUTTON_RESETROI             1085
#define IDC_BUTTON_RESELECT             1086
#define IDC_BUTTON_APPLY                1087
#define IDC_STATIC_CENTERX              1088
#define IDC_STATIC_CENTERY              1089
#define IDC_STATIC_RADIUS               1090
#define IDC_STATIC_ROIPARAMS_ROI1       1091
#define IDC_EDIT_TEXT_ROIPARAMS1_CENX   1092
#define IDC_EDIT_ROIPARAMS1_RADIUS      1093
#define IDC_STATIC_ROIPARAMS_ROI2       1094
#define IDC_EDIT_ROIPARAMS2_CENX        1095
#define IDC_EDIT_ROIPARAMS2_RADIUS      1096
#define IDC_EDIT_ROIPARAMS3_CENX        1097
#define IDC_EDIT_ROIPARAMS3_CENY        1098
#define IDC_EDIT_ROIPARAMS3_RADIUS      1099
#define IDC_STATIC_ROIPARAMSROI3        1100
#define ID_COPY                         1103
#define ID_CANCEL                       1104
#define IDC_BUTTON_SELECT               1107
#define IDC_COMBO_DATA_FORM             1108
#define IDC_BUTTON_RECONEXIT            1110
#define IDC_LIST_SCANNED_PROT_LIST      1111
#define IDC_STATIC_INVTI                1112
#define IDC_STATIC_SERIES_NAME          1116
#define IDC_STATIC_PIX_POS              1117
#define IDC_STATIC_ONE_BUTTON_PHASE_CORRECTION 1118
#define IDC_STATIC_DATA_FORM            1119
#define IDC_IMAGE_DATA_TYPE             1120
#define IDC_PHASE_CORRECTION            1121
#define IDC_SELECTED_PROTOCOL_DISPLAY   1122
#define IDC_RADIO_1STEQU                1123
#define IDC_RADIO_2NDEQU                1124
#define IDC_RADIO_3RDEQU                1125
#define IDC_EDIT_MAGNITUDE              1126
#define IDC_RADIO_4THEQU                1127
#define IDC_RADIO_5THEQU                1128
#define IDC_BUTTON_SAVE_ROI_DATA        1129
#define IDC_REAL_SELECT_BTN             1130
#define IDC_HIDE_BTN                    1131
#define IDC_MAGNITUDE_SELECT_BTN        1132
#define IDC_POLARITY_CORRECTION_BTN     1133
#define IDC_STATIC_MAGNITUDE            1134
#define IDC_STATIC_PROTOCOL             1135
#define IDC_CHECK_ADD_ROI_AVG           1136
#define IDC_EDIT_PROTOCOL               1137
#define IDC_BUTTON_PROT_SELECT          1139
#define IDC_BUTTON_APPLY_OFFSET         1140
#define IDC_STATIC_FRAME_NOISE_CORRECTION 1141
#define IDC_STATIC_NOISE_CORRECTION     1142
#define IDC_STATIC_NOISE_ROI1           1143
#define IDC_STATIC_NOISE_ROI2           1144
#define IDC_STATIC_OFFSET_CORRECTION    1145
#define IDC_STATIC_NOISE_CORRECTION_VALUE 1146
#define IDC_CHECK_NOISE_ROI1_DISLPAY    1147
#define IDC_CHECK_NOISE_ROI2_DISLPAY    1148
#define IDC_CHECK_OFFSET_CORRECTION_DISLPAY 1149
#define IDC_EDIT_NOISE_CORRECTION_VALUE 1150
#define IDC_STATIC_ROI4_PARAMS          1151
#define IDC_STATIC_ROI5_PARAMS          1152
#define IDC_EDIT_ROI4_CENX              1153
#define IDC_EDIT_ROI4_CENY              1154
#define IDC_EDIT_ROI4_RADIUS            1155
#define IDC_EDIT_ROI5_CENX              1156
#define IDC_EDIT_ROI5_CENY              1157
#define IDC_EDIT_ROI5_RADIUS            1158
#define IDC_CHECK_T1MAP                 1159
#define IDC_BUTTON_RECONSTRUCTION       1160
#define IDC_STATIC_WIDTH                1161
#define IDC_EDIT_WIDTH_ROI1             1162
#define IDC_EDIT_WIDTH_ROI2             1163
#define IDC_EDIT_WIDTH_ROI3             1164
#define IDC_EDIT_WIDTH_ROI4             1165
#define IDC_EDIT_A_FACTOR               1166
#define IDC_EDIT_B_FACTOR               1167
#define IDC_EDIT_M_FACTOR               1168
#define IDC_EDIT_N_FACTOR               1169
#define IDC_BUTTON_INITIAL_GUESS_APPLY  1170
#define IDC_STATIC_A_FCTOR              1171
#define IDC_STATIC_B_FACTOR             1172
#define IDC_STATIC_M_FACTOR             1173
#define IDC_STATIC_N_FACTOR             1174
#define IDC_CHECK_MANUAL_GUESS          1175
#define IDC_BUTTON_MANUAL_GUESS         1176
#define IDC_STATIC_AVERAGE_FILTER       1177
#define IDC_STATIC_SELECT_FILTER        1178
#define IDC_STATIC_FILTER_SIZE          1179
#define IDC_CHECK_CREATE_SERIES         1182
#define IDC_EDIT_FILTER_SIZE            1183
#define IDC_COMBO_SELECT_FILTER         1184
#define IDC_STATIC_CREATE_SERIES        1185
#define IDC_BUTTON_DATA_TYPE            1186
#define IDC_EDIT_DATA_TYPE              1187
#define IDC_STATIC_FILTERS              1188
#define IDC_EDIT_LABEL_MAGNITUDE        1189
#define IDC_BUTTON_SELECT_MAGNITUDE     1191
#define IDC_EDIT_LABEL_IMAGINARY        1192
#define IDC_EDIT_IMAGINARY              1193
#define IDC_BUTTON_SELECT_IMAGINARY     1194
#define IDC_EDIT_LABEL_REAL             1195
#define IDC_EDIT_REAL                   1196
#define IDC_BUTTON_SELECT_REAL          1197
#define IDC_BUTTON_CORRECT_PHASE_MANUAL 1198
#define IDC_STATIC_PHASE_CORRECTION_AUTO 1199
#define IDC_STATIC_LABEL_MAGNITUDE      1200
#define IDC_STATIC_LABEL_REAL           1201
#define IDC_STATIC_LABEL_IMAGINARY      1202
#define IDC_STATIC_IRS_MSG              1203
#define IDC_EDIT_SOURCE_PROT            1204
#define IDC_STATIC_SOURCE_PROT          1205
#define IDC_CHECK_DEFAULT_PARAM_SET_ROI 1206
#define IDC_SAVE_SET_ROI_PARAMS         1207
#define IDC_STATIC_ABOUT1               1208
#define IDC_STATIC_ABOUT2               1209
#define IDC_STATIC_ABOUT_ICON           1210
#define IDC_STATIC_PROT_FOR_RECON       1212
#define IDC_PROGRESS1                   1213
#define ID_OK                           1214
#define IDC_STATIC_PROGRESS             1215
#define IDC_BUTTON_APPLYTI              1216
#define ID_APPLY                        1217
#define IDC_STATIC_SET_TI_VALUE         1218
#define IDC_STATIC_TI_VALUES            1219
#define IDC_STATIC_MODE_SETTI           1220
#define IDC_RADIO_CALCMODE              1221
#define IDC_CHECK_ROI1                  1222
#define IDC_CHECK_ROI2                  1223
#define IDC_CHECKROI3                   1224
#define IDC_EDIT_ROI1VAL                1225
#define IDC_EDIT_ROI2_VAL               1226
#define IDC_EDIT_ROI3_VAL               1227
#define IDC_EDIT_AVG_VAL                1228
#define IDC_STATIC_AVGROI               1229
#define IDC_RADIO_VF_TIVAL              1230
#define IDC_EDIT_VFTIVALUE              1231
#define IDC_RADIO_INPUTTI               1233
#define IDC_EDIT_INPUTTI                1234
#define IDC_CHECK_OFFSET                1236
#define IDC_STATIC_MODES                1238
#define IDC_LIST_UNSCAN_PROTOCOL        1240
#define IDC_STATIC_ORIGINAL_TI          1241
#define IDC_STATIC_NEW_TI               1242
#define IDC_EDIT_ORIGINAL_TI            1243
#define IDC_EDIT_NEW_TI                 1244
#define IDC_STATIC_SEL_UNSCAN_PROT      1245
#define IDC_STATIC_ROIAVG               1246
#define IDC_SPIN_INPUT_TI               1249
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_OPTIONS_SETROI               32771
#define ID_OPTIONS_COPYROI              32772
#define ID_OPTIONS_RECONSTRUCTION       32773
#define ID_OPTIONS_POLARITYCORRECTION   32774
#define ID_OPTIONS_ADDOFFSET            32775
#define ID_OPTIONS_MANUAL_PHASE_CORR    32776
#define ID_HELP_ABOUT                   32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1250
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
