/*********************************************************************
 *
 *
 *
 *    File Overview:
 *      This file defines .
 *
 *********************************************************************/
#ifndef _RELIMITMSG_H
#define _RELIMITMSG_H

static struct
{
    unsigned int	code;
    char		*message;
} msgDefs[] =
{
    {PROMSG_REQ_TREE_ID,		"PROMSG_REQ_TREE_ID"},
    {PROMSG_CON_TREE_ID,		"PROMSG_CON_TREE_ID"},
    {PROMSG_ERROR,			"PROMSG_ERROR"},
    {PROMSG_UI_TREE_ACCESS_REQUEST,	"PROMSG_UI_TREE_ACCESS_REQUEST"},
    {PROMSG_CON_TREE_ACCESS_GRANTED,	"PROMSG_CON_TREE_ACCESS_GRANTED"},
    {PROMSG_UI_TREE_ACCESS_END,		"PROMSG_UI_TREE_ACCESS_END"},
    {PROMSG_CON_INHIBIT_SELECTIONS,	"PROMSG_CON_INHIBIT_SELECTIONS"},
    {PROMSG_CON_ALLOW_SELECTIONS,	"PROMSG_CON_ALLOW_SELECTIONS"},
    {PROMSG_CON_TREE_UPDATED,		"PROMSG_CON_TREE_UPDATED"},
    {PROMSG_CON_TREE_AVAILABLE,		"PROMSG_CON_TREE_AVAILABLE"},
    {PROMSG_CON_RAISE_WINDOW,		"PROMSG_CON_RAISE_WINDOW"},
    {PROMSG_UI_WINDOW_ID,		"PROMSG_UI_WINDOW_ID"},
    {PROMSG_UI_GATE_INTERVAL_REQUEST,	"PROMSG_UI_GATE_INTERVAL_REQUEST"},
    {PROMSG_CON_GATE_INTERVAL,		"PROMSG_CON_GATE_INTERVAL"},
    {PROMSG_CON_RELIMIT,		"PROMSG_CON_RELIMIT"},
    {PROMSG_LIM_RELIMIT_DONE,		"PROMSG_LIM_RELIMIT_DONE"},
    {PROMSG_CON_SAVE_TREE,		"PROMSG_CON_SAVE_TREE"},
    {PROMSG_LIM_SAVE_DONE,		"PROMSG_LIM_SAVE_DONE"},
    {PROMSG_CON_RELOAD_TREE,		"PROMSG_CON_RELOAD_TREE"},
    {PROMSG_CMD_EXIT,			"PROMSG_CMD_EXIT"},
    {PROMSG_CMD_SAVE_EXIT,		"PROMSG_CMD_SAVE_EXIT"},
    {PROMSG_CMD_START_UI,		"PROMSG_CMD_START_UI"},
    {PROMSG_CMD_QUEUE,			"PROMSG_CMD_QUEUE"},
    {PROMSG_CMD_QUEUE_EXIT,		"PROMSG_CMD_QUEUE_EXIT"},
    {PROMSG_CMD_QUEUE_NEXT,		"PROMSG_CMD_QUEUE_NEXT"},
    {PROMSG_CMD_NEXT_PROTOCOL,		"PROMSG_CMD_NEXT_PROTOCOL"},
    {PROMSG_CMD_CLOSE,			"PROMSG_CMD_CLOSE"},
    {PROMSG_CMD_REFRESH,		"PROMSG_CMD_REFRESH"},
    {PROMSG_CON_WINDOW_ID,		"PROMSG_CON_WINDOW_ID"},
    {PROMSG_PQM_QUEUE_DONE,		"PROMSG_PQM_QUEUE_DONE"},
    {PROMSG_PQM_NEXT_PROTOCOL_DONE,	"PROMSG_PQM_NEXT_PROTOCOL_DONE"},
    {PROMSG_PQM_NEXT_PROTOCOL_TRUE,	"PROMSG_PQM_NEXT_PROTOCOL_TRUE"},
    {PROMSG_PQM_NEXT_PROTOCOL_FALSE,	"PROMSG_PQM_NEXT_PROTOCOL_FALSE"},
    {PROMSG_PQM_LOCATOR_IMAGES_TRUE,	"PROMSG_PQM_LOCATOR_IMAGES_TRUE"},
    {PROMSG_PQM_LOCATOR_IMAGES_FALSE,	"PROMSG_PQM_LOCATOR_IMAGES_FALSE"},
    {PROMSG_PQM_REFRESH_DONE,		"PROMSG_PQM_REFRESH_DONE"},
    {PROMSG_CON_GATE_INTERVAL_REQUEST,	"PROMSG_CON_GATE_INTERVAL_REQUEST"},
    {PROMSG_PQM_GATE_INTERVAL,		"PROMSG_PQM_GATE_INTERVAL"},
    {PROMSG_CMD_PLAN_DUPLICATE,		"PROMSG_CMD_PLAN_DUPLICATE"},
};


#endif
